### ISSUE TITLE
Why are there multiple `Server` interfaces, and do we need them?

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#100]
In [tracker/tracker.go:28](https://github.com/chihaya/chihaya/blob/master/tracker/tracker.go#L27-L34) we define a `Server` interface with two methods: `Serve(string)` and `Stop()`. In [chihaya.go](https://github.com/chihaya/chihaya/blob/master/chihaya.go#L41-L44) there is another `server` interface, though unexported. This would not not surprise me a lot, but:

1. They are not the same: In `chihaya.go` the `Serve()` method has no parameter.
2. We import `"github.com/chihaya/chihaya/tracker"`, so why not use the interface defined there?

**Comment by jzelinskie** [comment]
I just added that code in `chihaya.go` and forgot that the `Server` definition in models exists. It should be updated to take a `config.config` for the serve parameter and used instead of the one-off interface in `chihaya.go`.

**Comment by mrd0ll4r** [comment]
If we do that, neither `*http.Server`, nor `*udp.Server` nor `*api.Server` will implement `tracker.Server` - they all get the config in their respective `NewServer` function. We could change their `Serve()` methods:

- `(*api.Server).Serve()` could be changed
- `(*http.Server).Serve()` could be changed, but is ugly because we'd have the config parameter propagated to `newAnnounce` and `newScrape` - we could keep the `config` field in the `http.Server` struct and set `s.config` in `Serve(config.Config)`, but I don't think that's the idea behind the `Serve()` method?
- `(*udp.Server).Serve()` is pretty much the same as `*http.Server`

What do we do?

**Comment by jzelinskie** [comment]
Yeah sorry -- I wasn't looking at the code once again... We can just make the interface in chihaya.go the one in models. I'll open a PR now.

**Comment by jzelinskie** [comment]
Removed in b6929a7632e640b5805bac06b726a30337d70534
