### ISSUE TITLE
tracker/models/peermap.go could be simplified

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#101]
In [tracker/models/peermap.go:46-64](https://github.com/chihaya/chihaya/blob/master/tracker/models/peermap.go#L46-L64): We could remove the `if pm.Config.PreferredSubnet` check, because `(*PeerMap) mask(net.IP) string` returns `""` for `!pm.Config.PreferredSubnet`

EDIT: Additionally, this causes some confusion, because `LookUp`, `Put` and `Delete` do not explicitly perform this check (but rather rely on `mask`)

**Comment by jzelinskie** [comment]
No further development on 1.0
