### ISSUE TITLE
if-else-else construct in peermap.go is confusing

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#102]
In [tracker/models/peermap.go:188-197](https://github.com/chihaya/chihaya/blob/master/tracker/models/peermap.go#L188-L197): Why do we use exactly these conditions? For example, why is there not a case for `!ann.Config.RespectAF && peer.HasIPv6()`? Or could we maybe simplify the cases already present?

**Comment by jzelinskie** [comment]
This code has been frozen and won't be in 2.0.
