### ISSUE TITLE
Use pointers for PeerLists in AppendPeers?

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#103]
In [tracker/models/peermap.go:148](https://github.com/chihaya/chihaya/blob/master/tracker/models/peermap.go#L148): We could change the `ipv4s, ipv6s PeerList` parameters to be of type `*PeerList`, this should reduce the garbage generated in [tracker/announce.go:285-296](https://github.com/chihaya/chihaya/blob/master/tracker/announce.go#L285-L296), if my thinking is correct.

**Comment by jzelinskie** [comment]
No further development on 1.0.
