### ISSUE TITLE
JSON tags should be normalized and cleaned up

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#104]
We should normalize all of our JSON tags (and remove unused ones), for example:

1. [stats/stats.go:69-103](https://github.com/chihaya/chihaya/blob/master/stats/stats.go#L69-L103) uses capital first letters and dots
2. [the config](https://github.com/chihaya/chihaya/blob/master/example_config.json) uses all-lowercase and underscores
3. [tracker/models/models.go:89-98](https://github.com/chihaya/chihaya/blob/master/tracker/models/models.go#L89-L98) uses all-lowercase and underscores, but I'm not even sure if these structs are serialized to JSON anywhere?

AFAIK JSON keys should be in _camelCase_, there is a discussion about this on [stackoverflow](http://stackoverflow.com/questions/5543490/json-naming-convention).

__EDIT__: Completely forgot to mention it, but: This will definitely break backwards-compatibility

**Comment by jzelinskie** [comment]
the models get serialized in the API

**Comment by mrd0ll4r** [comment]
I think the `ID` fields (`Peer.ID` and `Torrent.ID`) should be lowercase, but it looks strange - your opinion about this?

**Comment by jzelinskie** [comment]
Yep, sorry that's a Go-ism that `ID` should be capitalized. It definitely isn't in JS.

**Comment by mrd0ll4r** [comment]
Sorry for causing all that trouble, looks fine to me now!

**Comment by jzelinskie** [comment]
In the future, you should comment on the PR and not the issue.
