### ISSUE TITLE
udp: Do we allow connection IDs that are up to two hours old?

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#109]
From [BEP 15](http://bittorrent.org/beps/bep_0015.html):

> A client can use a connection ID until one minute after it has received it. Trackers should accept the connection ID until two minutes after it has been send.

As far as I understand, we accept connection IDs that are up to two _hours_ old (because we validate against the current and the previous IV in [`udp.Matches`](https://github.com/chihaya/chihaya/blob/master/udp/connection.go#L65-L77), and we cycle the IV every hour in [udp/udp.go](https://github.com/chihaya/chihaya/blob/master/udp/udp.go#L98-L106)).

I'm not sure if the two minutes thing was maybe overriden by another BEP or something, so please correct me if I'm wrong.

__EDIT__: In case I got everything right, I propose to just rotate the IV every minute, that should fix this easily. Give me a go and I'll do it

**Comment by jzelinskie** [comment]
The new connection IDs are implemented using truncated HMAC and strictly follow the spec for lifetimes.
