### ISSUE TITLE
udp: check if server already started is racy

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#113]
The check for `s.sock != nil` in [udp/udp.go:33-35](https://github.com/chihaya/chihaya/blob/master/udp/udp.go#L33-L55) is racy, we should do that differently, probably with the `s.booting` channel.

**Comment by jzelinskie** [comment]
The UDP server type itself is not meant to be thread-safe. You can't have one instance shared by two threads and call `Serve()` on both and assume things will work correctly. This check is only supposed to stop you from calling `Serve()` twice.

**Comment by mrd0ll4r** [comment]
That makes sense, I'll close this :-)
