### ISSUE TITLE
Generate example_config.json from the default config

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#120]
As per @jzelinskie's suggestion, we should generate the example_config.json from the default config. A few things to do before that:

I've noticed the example_config.json does not have the same content as the default config (see the client whitelist, maybe there are more differences). I think we should add that whitelist to the default config (and leave it deactivated), so, if we generate the example_config.json from the default config, it'll still be there, because it's a good example.

**Comment by jzelinskie** [comment]
Starting with v2.0.0, there should be no default config built into the binary anymore.
