### ISSUE TITLE
Move towards a modular architecture

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#123]
@jzelinskie and I had a chat about the internal architecture of, especially, the tracker.

They way we handle announces (and scrapes) now is by calling a lot of methods one after another that somehow modify the announce, the storage, the backend and whatnot, but it's pretty messed up.
Because it's like that right now, we have lots of potential bugs and memory issues that we just can not see or fix.

So we came up with the idea of a modular/context/middleware/handler-based approach: (might need renaming)
- have UDP and HTTP both produce an announce (or scrape) that is completely filled with all the data they can gather
- have that announce (maybe wrapped in something like a context, see example below) be handled by a chain of middlewares and a handler at the end
- have multiple middlewares in the chain that perform checks (e.g. blacklisting/whitelisting, passkeys, ...) and modify or abort the request
- have one handler at the end of the chain that handles the announce as simply as possible

Or something like that.

I originally go the idea from the brilliant web framework [gin](https://github.com/gin-gonic/gin), I think we should take a very similar approach to middlewares and contexts to what they've done. For example, look at the way they implement [custom middlewares](https://github.com/gin-gonic/gin/blob/master/README.md#custom-middleware) or any middlewares, for that matter.

For us, this means we would first remove a lot of stuff (private tracker mode, preferred subnets, ...) and simplify what we have so far. Then, I think we should define very clever types for contexts and middlewares (and maybe have a look at the current announce and scrape model). If all that is done, it should be easy to re-implement the features we removed on top of the new architecture.

This issue is meant as a discussion about the proposal and the steps necessary to get there.

**Comment by mrd0ll4r** [comment]
I thought about the design of middlewares, will take infohash blacklisting as an example:

- we'll have to include and configure it in the config:

        {  
           "middlewares":[  
              "infohash-blacklist"  //order is important
           ],
           "middlewareConfigs":{  
              "infohash-blacklist":{  
                 "dbconn":"mysql://user:pass@host:schema" //content is whatever that middleware needs
              }
           }
        }

    Which translates to a structure like

        type MWConf map[string]string
        
        type config struct {
            Middlewares       []string                     `json:"middlewares"`
            MiddlewareConfigs map[string]MWConf            `json:"middlewareConfigs"`
        }

- have the middlewares register in their `init()` functions. Maybe a middleware could look like this:

        type HandlerFunc func(*Context) error

        type Middleware interface{
	        New(MWConf) (MWImpl,error)
            Endpoints() []api.Endpoint //read on :)
        }

        type MWImpl interface {
	        Handler() HandlerFunc
        }

On `New()`, infohash-blacklist would connect to the db and load the blacklist into memory. (maybe define the table name and layout in the README for infohash-blacklist to avoid conflicts?)
Now, the problem with infohash blacklisting is: The blacklist will change, and we don't want to restart chihaya everytime it does. I see two solutions here:
- add API endpoints `/middlewares/infohash-blacklist/add` and `/middlewares/infohash-blacklist/remove`, which would add/remove the infohashes to the in-memory storage and the db
- add API endpoint `/middlewares/infohash-blacklist/refresh`, which would re-read the db -> add new infohashes to the db first, then call the API method

I think this is a decision we should make for every middleware separately.
For both cases, we need to be able to add API endpoints from a middleware. We could include this in the middleware registration, That's where the `Endpoints()` function comes into play:

    package api

    type Endpoint struct {
    	Name string //for logging
    	Method string
    	Route string
    	Handler HandlerFunc
    }

So, to add a middleware:

1. The middleware is imported (probably as `_`)
2. The middleware `Register()`s with the tracker on `init()`
3. During tracker setup, for every middleware:
    1. The tracker calls `New()` with the appropriate config
    2. If that works, the tracker gets the `Endpoints()` and adds them to the API
    3. The tracker adds the `MWImpl.Handler()` to the chain of middlewares

I hope I could express what I was thinking, feel free to comment

**Comment by jzelinskie** [comment]
I've compiled my work so far into a framework that we can import and use in chihaya.
Currently, the framework only models the data and the protocol-agnostic middleware.
How to register middleware dynamically will be the job of chihaya.
You can see my progress over at https://github.com/jzelinskie/otoshi

**Comment by mrd0ll4r** [comment]
Again, great work! I've looked at it more in-depth and have a few more things:

- `AnnounceRequest.NumWant` should probably be an `int` rather than `uint16` - I didn't find the BEP specifying numWant, but [BEP 15](http://bittorrent.org/beps/bep_0015.html) uses a 32 bit integer for `num_want`. I guess you had in mind that `numWant > 2^16` does not make sense, I agree. I'm undecided - if you leave it `uint16`, maybe add a note indicating why.

- We could specify something like a `type Event int` and have the few events `const` somewhere, instead of passing strings in `AnnounceRequest.Event`.

- I will do some benchmarks regarding `url.URL` parsing, if it turns out to be slow, we should include something like `Get(string) string` or some other way to get URL parameters and query strings for announces (and possibly scrapes, but that only works for HTTP).

    The more I think about this, the more my head hurts. Can we force a client to send for example an authKey as an HTTP parameter, i.e. can we use a tracker url like `http://....:/announce?auth=<key>` in a torrent and it works? I know it works for UDP, but I'm not sure about HTTP. Ocelot (and chihaya in private mode) for example uses tracker urls like `http://..../<key>/announce`, maybe there's a reason for it. And if there is, we are in a difficult situation with the private-mode middleware, as it would have to change the listener routes from `/announce` and `/scrape` to `/:passkey/announce` and `/:passkey/scrape`, but that's impossible for a middleware.

- I have one major issue though: How to write something like a performance-logger middleware? I'm thinking of a logger (who, what, when) that also logs how long it took to handle the request. 
Gin does this by providing `(*Context) Next()` to continue calling the middleware chain (and the handler) from within a middleware (the simply use an index of where they are right now, so they don't run into problems when calling `Next()` multiple times):

        // Next should be used only inside middleware.
        // It executes the pending handlers in the chain inside the calling handler.
        // See example in github.
        func (c *Context) Next() {
        	c.index++
        	s := int8(len(c.handlers))
        	for ; c.index < s; c.index++ {
        		c.handlers[c.index](c)
        	}
        }

    (from [context.go](https://github.com/gin-gonic/gin/blob/master/context.go#L88-L97)) (This is also how they handle requests in general, see [here](https://github.com/gin-gonic/gin/blob/master/gin.go#L294))

    We could either do something like that, or be able to store data in contexts, and then add a pre-logger at the beginning of the chain that puts the start time in the context and an ending-logger that calculates the time. `context.Context` has `Value(interface{}) interface{}`, but it looks cumbersome and the godoc suggests:

        // Use context values only for request-scoped data that transits
        // processes and API boundaries, not for passing optional parameters to
        // functions.

    Additionally, if we do something like the latter approach, we'd be able to define middlewares after the actual handler has run. That could be cool, because we can then modify the response before it is sent, but I don't know if it's the right thing to do...(and it should add a lot of confusion). Maybe something like FBs preferred subnets could be implemented like that? Maybe we should restrict middlewares after the handler to only change the content of the response, not cancel the request, or something like that?

- The `TransportWriter` is still a mystery to me: Do you want to have one per transport (UDP, HTTP), or one per request? Or maybe even something else? Because I don't understand how, if you mean one per transport, the Writer knows the destination to write to. `WriteAnnounceResponse` is okay, it could use the `AnnounceRequest.Peer` I guess, but what if the `Peer` has an overridden IP address? `WriteError` and `WriteScrapeResponse`: I have no idea how they should work...

- I think we should make a small wrapper around `context.Context` with functions like `AbortWithError(error)` that closes `Done()` and makes `Err()` return an error. Dunno if that's a job for chihaya or otoshi.

- JSON tags?

- And finally: `ServeAnnounce` and `ServeScrape` should check the `context.Context` stuff, especially the `Done()` channel I think, maybe even more.

**Comment by jzelinskie** [comment]
* NumWant is an effort to save memory, yes.
* Event Type, I will add this.
* Passkeys as a query parameter is ideally better than having it in the URL path. We need to test this with a bunch of the popular clients
* Logging is still an open question. Right now, chihaya logs how long it takes to parse a request, handle the request, and write the response as one single duration. We can either log the time to handle the response in otoshi (i.e. at the start and end of ServeScrape or ServeAnnounce) or leave it to chihaya to log similarly to how we do now. I'm not convinced we need to thread log state through the middleware.
* TransportWriter is exactly the same as tracker.Writer in chihaya. It's so that you can run one tracker instance and handle multiple protocols. An HTTP server always passes a TransportWriter that's wrapping the http.ResponseWriter for their request and a UDP server is wrapping a []byte that will be their response to their request. The IP address is not the target for the request, that's just metadata we're saving. In the BitTorrent protocol, you don't actually care about the port/IP where the messages come from, only the ones they advertise you to use.
* Context wrapping I need to think about more first. Right now we check to see if the middleware has returned a `ClientError`, which flags us to write the error to the client and abort the rest of the middleware.
* JSON tags, I will add this.
* Once again, yeah I need to consider how much we want to integrate with context.Context

**Comment by mrd0ll4r** [comment]
I agree with the passkeys as query parameters. I've also just done some benchmarks with the stdlib and our parsing, results are at https://github.com/mrd0ll4r/urlparse.

Our implementation is very fast, because we do not use slices as values, i.e. we only use the last occurrence of a parameter for the value. I think that's okay for our use case right now :)

**Comment by mrd0ll4r** [comment]
Passkeys as a query parameter:

- uTorrent (3.4.2): works
- rtorrent 0.9.4 (libtorrent 0.13.4): works

will update this if I get my hands on more data...

**Comment by jzelinskie** [comment]
I guess I can close this since this is finally in master.
