### ISSUE TITLE
Have the complete URL stored in the announce

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#124]
We should store the complete URL that was requested somewhere in the announce. This enables us to store stuff in the announce URL and use it when we handle the announce. Because of BEP41, we can do that for both HTTP and UDP.

Note that it does not have to be stored in the announce, but it should be passed to the tracker somehow :)

**Comment by jzelinskie** [comment]
The design in 2.0 takes this into account.
