### ISSUE TITLE
tracker reports "torrent does not exist" whith createOnAnnounce enabled

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#126]
Running chihaya with the default config and bombarding it with tbomb, I got this:

    ...
    announce: tracker responded with error: torrent does not exist            1
    ...

I have no idea what infohash tbomb sent, but chihaya also reports:

    2015/12/01 16:15:23.077396 WARNING: [UDP -    2.383s] announce 127.0.0.1:56552 (torrent does not exist)

Any ideas? tbomb sends infohashes between `00000000000000000000` and `00007fffffffffffffff`, so I guess they should not be invalid. My best guess right now is that the torrent was reaped between being initially found and processed further (i.e. an error was returned when the peer was added to the torrent, but by then it was already reaped).

Of course this is not reproducible, and I had it running on warning level only.

**Comment by jzelinskie** [comment]
>I had it running on warning level only.

:crying_cat_face: 

Yeah, your hypothesis is likely to be correct because we don't hold a lock on the torrent during the whole request time so that we can have simultaneous announces on the same torrent.

**Comment by mrd0ll4r** [comment]
Sorry, was testing performance :D
Alright, I guess this is `wont-fix` or `shouldn't-fix`, will close.
