### ISSUE TITLE
Potential Middleware

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#145]
- [x] Client Whitelist/Blacklist
- [x] IP Whitelist/Blacklist
- [x] Infohash Whitelist/Blacklist
- [ ] Preferred Subnets
- [ ] JWT Verification
- [x] Basic Response

**Comment by mrd0ll4r** [comment]
IP Whitelist/Blacklist only needs some tests, Infohash Whitelist/Blacklist has a PR open

I'll implement:

- [ ] Deniability (insert random peers to a response)
- [ ] Ratelimit

**Comment by joshdekock** [comment]
- [ ] torrent caching (like [torrage](http://torrage.info/) but done automatically) 

_Although I'm not sure if this should be a server instead, as it will need to be able to seed a metafile asynchronously to the middleware stack (not that this couldn't be achieved with go statements)_

Also, just as a heads up, I'm implementing Basic Response currently

**Comment by jzelinskie** [comment]
I don't understand what you mean by torrent caching. If I understand it correctly, it's just a lookup for piece data given an infohash. The BitTorrent DHT already does this.

If I was hypothetically trying to download something and I only had the infohash, I'd just open it with a client using a magnet URI and use the DHT to get metadata and then I just add _all_ the public trackers I know about to try and find peers.

**Comment by joshdekock** [comment]
Yeah, I'm not sure I thought about it properly

**Comment by jzelinskie** [comment]
Going to close this since there isn't much discussion going on, the topic is super general, and most of these have been implemented.
