### ISSUE TITLE
Integrate 'Poke' tool into continuous integration

### ISSUE THREAD

**Issue by eintw1ck** [chihaya/chihaya#151]
At the moment it's not tested at all

**Comment by mrd0ll4r** [comment]
Just to throw that in here: I wrote [poke](https://github.com/mrd0ll4r/poke) to test chihaya as a black box (currently only via HTTP). We could use that (or the tests within), it should cover `AnnouncePeers` a few times. We could use something like described [here](https://www.elastic.co/blog/code-coverage-for-your-golang-system-tests) to get the coverage for that "system test".

**Comment by jzelinskie** [comment]
I wouldn't be opposed to running poke briefly in our travis-ci instances.
