### ISSUE TITLE
interfaces

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#156]
[interfacer](https://github.com/mvdan/interfacer) spits out this:

```
pkg/bencode/decoder.go:116:21: r can be io.ByteScanner
server/http/request.go:109:18: q can be chihaya.Params
server/http/writer.go:27:28: w can be io.Writer
server/http/writer.go:71:26: w can be io.Writer
```

Just FYI, dunno if we should actually change them.

**Comment by jzelinskie** [comment]
The last two don't really make sense, but the first two do. I'll do it right now.
