### ISSUE TITLE
Separate IPv4 and IPv6 PeerStores?

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#191]
Maybe we should have a separate `PeerStore` for IPv4 and IPv6 peers. This would require some more memory but also make retrieving peers easier.

The reason I'm bringing this up: the `memory` implementation currently just returns random peers from a swarm without looking at the address type. This makes an IPv6 be very improbable to find if there is a majority of IPv4 peers and vice versa.

**Comment by jzelinskie** [comment]
I think it would lead to a lot of code duplication. I'd rather have a more simple interface that has documentation about implicit functionality such as distinction between IPv4/IPv6 and garbage collection.

**Comment by mrd0ll4r** [comment]
Yeah this doesn't really apply to the refactor branch anymore as we now explicitly separate IPv4 and IPv6 swarms, closing.
