### ISSUE TITLE
When is next release?

### ISSUE THREAD

**Issue by sivachandran** [chihaya/chihaya#202]
Hi,

I find huge difference between release v1.0.0 and master. As I want to run a stable version I am sticking  with v1.0.0 but really looking forward for next release as master contains many improvements.

Can you tell when is the next release is planned? Is there are roadmap that I can refer?

@jzelinskie @pushrax

**Comment by jzelinskie** [comment]
Master is actually behind by a lot, too. We're currently working on the `refactor` branch. Before that gets merged in and we cut a release we still need to implement:
* IPv6 for UDP frontend
* bittorrent.Params ([BEP41](http://www.bittorrent.org/beps/bep_0041.html)) for UDP frontend 
* JWT middleware
* infohash whitelist/blacklist middleware

Sorry it's taken a long time to get another major release, but we've been trying to find a solid foundation for creating middleware that can still be performant for people that don't need any expensive features.

**Comment by cooperlees** [comment]
Let me know if you want anything stress tested etc. 😄

**Comment by sudsred** [comment]
Hi Jimmy and Justin,

I'm looking to add a redis storage function for memory amongst other things. I like pre-release v2.0.0-rc.1. Is that a stable enough tag to fork from? Do you have any updates on when the release is coming as well? 

Thanks.

@jzelinskie @pushrax

**Comment by mrd0ll4r** [comment]
Hey @sudsred,

imho the storage interface of v2.0.0-rc.1 is stable enough to implement the redis storage.
Make sure to watch the project though, in case we do make changes.

Also please let us know of the end product, in case you plan to open-source it. A redis storage sounds useful for the general public :)

**Comment by jzelinskie** [comment]
Hey there, we've tagged a few remaining issues as 2.0 milestone. After these issues are complete, we'll be cutting a stable 2.0 release!
