### ISSUE TITLE
support reloading config via unix signal

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#215]
Given a SIGHUP, I think chihaya should shutdown everything except for the peer store, and then start back up with a newly parsed config.

**Comment by mrd0ll4r** [comment]
Sounds like a good plan.
(Sent this on irc, but adding it here to have it in the issue): Does that work with docker?

**Comment by jzelinskie** [comment]
Yeah, you can use `docker kill --signal`.
