### ISSUE TITLE
Implement the final middleware/response middleware

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#216]
We need to implement the final middleware/the middleware the adds all the mandatory fields to a scrape or announce.

We should probably export a key that, if present in the context, stops the final middleware from setting these fields.

**Comment by jzelinskie** [comment]
>We should probably export a key that, if present in the context, stops the final middleware from setting these fields.

Considering we pass around a pointer to a response object, if we can disambiguate an unset value from a set value, we should be able to just look at that rather than stuffing things into the context.

**Comment by mrd0ll4r** [comment]
If we do things like setting a slice to nil rather than to length zero that makes recycling our response structs harder because we cannot just truncate the slice to zero but have to set it to nil (and reallocate).
