### ISSUE TITLE
JWT middleware needs to get initial JWT set

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#225]
(Untested, from code only)

The JWT middleware works with an empty set of keys until it runs the update logic in the goroutine for the first time. We should probably just attempt to update in the constructor, before starting the goroutine.

**Comment by jzelinskie** [comment]
Yea, I forgot to port this logic: https://github.com/chihaya/chihaya/blob/release-v1.0/tracker/jwt.go#L27
