### ISSUE TITLE
`net.ParseIP` parses IPv4 addresses to 16-byte `net.IP`s

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#230]
This becomes a problem for the HTTP server (e.g. it uses the remote address of the HTTP request (or some other source for a string-representation of the remote's IP) and calls `net.ParseIP` on it).

This 16-byte IPv4-in-IPv6 address then moves through the logic and creates all kinds of problems.

**Comment by jzelinskie** [comment]
Useful SO: http://stackoverflow.com/a/22751285

**Comment by mrd0ll4r** [comment]
I propose to add a sanitation (sanitization?) hook as the first hook for announces. It tests whether `To4() != nil` once and sets the IP to its 4-byte equivalent. I'll open a PR...
