### ISSUE TITLE
Use testify/require for all tests

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#239]
We should make all our tests use `testify/require`. Should be better than `assert` because the tests actually fail.

**Comment by jzelinskie** [comment]
Tests without require:
- [ ] bittorrent/client_id_test.go
- [ ] bittorrent/event_test.go
- [ ] bittorrent/params_test.go
- [ ] frontend/http/bencode/decoder_test.go
- [ ] http/bencode/encoder_test.go
- [ ] frontend/http/writer_test.go
- [ ] frontend/udp/connection_id_test.go
- [ ] frontend/udp/parser_test.go
- [x] middleware/varinterval/varinterval_test.go
- [x] storage/storage_tests.go
