### ISSUE TITLE
internal error when client provides invalid infohash

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#250]
CoreOS has chihaya v2 in prod now 🎉 
While testing it I got the following error when I provided chihaya a bogus infohash: 

```
time="2016-10-28T21:47:02Z" level=error msg="http: internal error: query: invalid infohash"
```

We still return a valid failure_reason and the binary doesn't crash or anything, but this shouldn't be an internal error.

**Comment by mrd0ll4r** [comment]
> CoreOS has chihaya v2 in prod now :tada: 

nice!
