### ISSUE TITLE
Add an IP to scrapes?

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#264]
I think it could be useful to add a `bittorrent.IP` to scrapes. This enables us to have a "normal" way of telling whether the Scrape is IPv6 or IPv4, without using the `context`. Because Scrapes are never saved, I don't think it's gonna hurt to include another field.

Thoughts?

**Comment by jzelinskie** [comment]
I like this idea, but I'd have to confirm with how a few of the major clients function with scraping. Scraping was designed before the idea of dynamically flipping between IPv4 and IPv6 swarms based on the provided IP address. Ideally we could add a whole `Peer` to the `ScrapeRequest`. If clients don't send an IP parameter, then we'll basically have to fallback to relying on the RemoteAddr for determining what Swarm they care about.

If everything closely follows [the spec](http://bittorrent.org/beps/bep_0048.html), we'd be out of luck. If this is not the case, maybe we can alter the spec and convince some big libraries to change over.

**Comment by mrd0ll4r** [comment]
I don't see what the clients have to do with this? If I understood you correctly, you want to check whether clients send an IP parameter for scrapes, right? From what I can remember, neither libtorrent nor uTorrent do this by default.
We won't be able to build a `Peer` because we're missing PeerID and Port. I don't think the spec will be changed ("not necessary for Scrapes", "bloats requests"), so all we have is the IP from the RemoteAddr (or a HTTP header, in case of reverse-proxying).

Right now we determine this from the RemoteAddr and set a boolean in the Context, which I expect to be slow. Moving to the IP/AddressFamily approach of a `bittorrent.IP` embedded in the scrape would probably be faster and would also move this messiness from the frontends to the sanitization hook (I noticed there that we can't use it for scrapes now).

**Comment by jzelinskie** [comment]
re:clients: yea, it's been a while since I thought about this stuff and it is a shame that scrapes don't send an IP.

re:chihaya: Okay, we're on the same page. I would prefer adding an AF to the ScrapeRequest rather than setting a context value.

**Comment by mrd0ll4r** [comment]
Fixed in #258
