### ISSUE TITLE
Is the website valuable?

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#266]
Chihaya isn't really consumer software. Do we think the website is too much to maintain?
Should the domain just point here and we can collect documentation in markdown in a single directory?

**Comment by mrd0ll4r** [comment]
I'd be in favor of that. It also has the advantage that

- whoever clones the repository gets all the documentation
- we only have to maintain one repository (we can have documentation PRs in the main repository)

**Comment by jzelinskie** [comment]
Fixed in #270 and #273
