### ISSUE TITLE
Prometheus has action=action metric floating around

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#271]
This ([frontend/udp/frontend.go:23](https://github.com/chihaya/chihaya/blob/master/frontend/udp/frontend.go#L23)) line causes prometheus to have one entry with `action=action` floating around. This is somewhat annoying, because it also creates all the quantile buckets (?), which are never used again. Same applies to HTTP. 

Can we get rid of that?

**Comment by jzelinskie** [comment]
Looks like a copy paste mistake.
