### ISSUE TITLE
Natively Support TLS/SSL For HTTPS

### ISSUE THREAD

**Issue by cooperlees** [chihaya/chihaya#283]
I'd like to run chihaya listening on http + https, and not need nginx etc. - I am a HTTPS noob so here are a few questions. tl;dr - What do you think is the best way to implement this?

- Is there a way we can run it on the same  port or does it have to be on a seperate port so we can direct it to different code etc.?
- Does libtorrent etc. just work with https announces today? Pretty sure they do
- Any other gotchas running SSL/TLS you can share?

**Comment by jzelinskie** [comment]
>Is there a way we can run it on the same port or does it have to be on a seperate port so we can direct it to different code etc.?

TLS can just be further configuration for the HTTP frontend. It would replace listening via plain HTTP, but you could specify any port.

>Does libtorrent etc. just work with https announces today? Pretty sure they do

libtorrent-based clients should work perfectly fine with this

>Any other gotchas running SSL/TLS you can share?

If you're using self-signed certificates or certificates from a CA that isn't installed on the clients, they'll fail to connect until you do install the certificate.
