### ISSUE TITLE
some part of client requests being unescaped incorrectly

### ISSUE THREAD

**Issue by Aranjedeath** [chihaya/chihaya#289]
I have found these lines in my console log after launching chihaya
```
ERRO[512513] http: internal error: invalid URL escape "%V\xbc"
ERRO[553108] http: internal error: invalid URL escape "%\xbaC"
ERRO[858096] http: internal error: invalid URL escape "%DT"
ERRO[943056] http: internal error: invalid URL escape "%>a"
ERRO[948997] http: internal error: invalid URL escape "%\xbdB"
```

Some client is probably sending crap data that is being escaped wrong or incorrectly. @jzelinskie says perhaps it should rightly reject the data as invalid, whatever it is.

**Comment by jzelinskie** [comment]
My intuition is that this is garbage data and this error should be handled earlier such that the code returns a ClientError containing "invalid infohash/whatever".
