### ISSUE TITLE
Prometheus records wrong address families for UDP/HTTP announces and UDP connects

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#293]
We don't set the `AddressFamily`, so it always defaults to `IPv4` for announces.

**Comment by jzelinskie** [comment]
Are we sure this is the case? I may be misunderstanding the issue, but it looks like [UDP](https://github.com/chihaya/chihaya/blob/82d79e5113ebc4dec8198909d3421b4bd9416d38/frontend/udp/frontend.go#L236) and [HTTP](https://github.com/chihaya/chihaya/blob/82d79e5113ebc4dec8198909d3421b4bd9416d38/frontend/http/frontend.go#L170) use the parsed IP's AddressFamily.

**Comment by mrd0ll4r** [comment]
Well, we only set the `bittorrent.IP.IP` field, see [HTTP](https://github.com/chihaya/chihaya/blob/master/frontend/http/parser.go#L77-L80), [UDP](https://github.com/chihaya/chihaya/blob/master/frontend/udp/parser.go#L104). We moved the AddressFamily deduction to the sanitization middleware...

**Comment by jzelinskie** [comment]
Ah! I understand now. Yeah, I'd like to see the sanitization middleware just turned into a function that's a part of the `bittorrent`, then we can just have frontends call that, rather than adding another middleware layer.

**Comment by mrd0ll4r** [comment]
Oh now I get how you meant that. Yeah that sounds like a good plan. The function needs all the limiting parameters though, so we'd have to figure out how to cleverly specify them in the config in one place and pass them to the frontend. Maybe just a struct in `bittorrent` that holds these limits? (max scrape, max numwant,...)

**Comment by jzelinskie** [comment]
I started working on [a branch for this](https://github.com/jzelinskie/chihaya/tree/sanitize-no-mw) the other night. PTAL, since it's a bit more invasive than you might think due to having to pass around the config state.

**Comment by mrd0ll4r** [comment]
Also UDP connects are always recorded with `Unknown` address family.

**Comment by jzelinskie** [comment]
wow, that's insidious, did github auto-close this from the PR description?

**Comment by mrd0ll4r** [comment]
Yup

**Comment by mrd0ll4r** [comment]
Fat-fingered the close and comment button.. damn

**Comment by mrd0ll4r** [comment]
Update: There are no wrong address families anymore. Errors are missing an address family, but that's fine for now.
The only thing left to fix is UDP connects - they currently have `Unknown` but we should give them the proper address family.
