### ISSUE TITLE
Build on Windows fails

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#302]
... because Windows does not have `SIGUSR` signals. It has `SIGHUP`, we could abuse that, but I don't like it. Maybe use build tags to use `SIGHUP` on Windows and `SIGUSR1` on any sane system?

**Comment by jzelinskie** [comment]
I asked someone the other day and they said that using signals like that isn't something that people do on Windows. I'll have to find out more info.

**Comment by kice** [comment]
I think you can just remove that line to have a successful build on Windows.

https://github.com/chihaya/chihaya/blob/master/cmd/chihaya/main.go#L143

**Comment by mrd0ll4r** [comment]
Yes, that is correct, but we can't ask all Windows users to edit the source before compiling.

**Comment by kice** [comment]
I think I it is a good idea to create a version for Windows users. BTW, I got garbled log output on cmd.exe https://github.com/sirupsen/logrus/issues/496.

**Comment by jzelinskie** [comment]
I'm actually very unfamiliar with Windows. When you ^C to shutdown a running binary, what happens? On Unix, a signal is sent to the process, but Windows doesn't have signals. What is the proper way to hook into events like this on Windows?

**Comment by mrd0ll4r** [comment]
It seems like a bunch of signals do work on Windows, for example SIGINT (see https://github.com/golang/go/blob/master/src/syscall/ztypes_windows.go#L53). It just doesn't have SIGUSR signals. We could abuse SIGHUP for config reloading, I guess, but it just feels hacky.

**Comment by jzelinskie** [comment]
We're going to move forward by adding a signals_windows.go file that users SIGHUP over SIGUSR1 to resolve this issue.
