### ISSUE TITLE
TrackerLogic should return modified Contexts

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#304]
The `HandleAnnounce` and `HandleScrape` methods call PreHooks, which update the context given to them and return the updated version. These methods should at the end return the fully updated `context.Context`, so that frontends can pass it to `AfterAnnounce` and `AfterScrape`.

**Comment by cedricgc** [comment]
Is this for both HTTP and UDP frontends?

**Comment by mrd0ll4r** [comment]
Yes, we need this for both frontends. The problem is that the tracker logic doesn't return the modified context, so [frontends have to create a new one](https://github.com/chihaya/chihaya/blob/master/frontend/udp/frontend.go#L298).

**Comment by cedricgc** [comment]
Can I change the TrackerLogic interface for `HandleAnnounce` and `HandleScrape` to return  context.Context? Should it be first or second return position?

[In the for loop for the middleware.go implementations](https://github.com/chihaya/chihaya/blob/cb55019ab8a44c74bf3f6fa0e23dd5fd2ecbb7d0/middleware/middleware.go#L58) if there is an error halfway through the loop should I return the context up to that point or nil?

ex. `ctx, nil, err` vs `nil, nil, err`

**Comment by mrd0ll4r** [comment]
> Can I change the TrackerLogic interface for HandleAnnounce and HandleScrape to return context.Context? Should it be first or second return position?

Yes, make it the first.

> In the for loop for the middleware.go implementations if there is an error halfway through the loop should I return the context up to that point or nil?

I think it should return `nil` in that case.
