### ISSUE TITLE
Restart logic fails if debug logging is enabled

### ISSUE THREAD

**Issue by TheOriginalWinCat** [chihaya/chihaya#309]
If I send a restart signal when debug logging is enabled it fails to restart as it tries to bind twice.

here is a log of such behavior: 

> level = debug msg = "debug logging enabled"
> level = info msg = "started serving HTTP on 0.0.0.0:6881"
> level = info msg = "started serving prometheus stats on 0.0.0.0:6880"
> level = info msg = "Got signal to restart"
> level = debug msg = "Stopping frontends"
> level = debug msg = "Stopping logic"
> level = debug msg = "Restarting logic"
> level = debug msg = "Restarting frontends"
> level = debug msg = "Successfully restarted"
> level = info msg = "started serving HTTP on 0.0.0.0:6881"
> level = debug msg = "Stopping frontends"
> level = debug msg = "Stopping logic"
> level = debug msg = "Stopping storage"
> level = debug msg = "Stopping frontends"
> level = debug msg = "Stopping logic"
> level = debug msg = "Stopping storage"
> level = fatal msg = "http: failed to run HTTP server: listen tcp 0.0.0.0:6881: bind: address already in use"

So from the looks of things it seams to be running the quit or shutdown logic also.
In a attempt to confirm this I added logging to the quit and shutdown statements like so:

`

			case <-quit:

				log.Debug("quit signal")

				stop(udpFrontend, httpFrontend, logic, errChan, peerStore)

			case <-shutdown:

				log.Debug("shutdown signal")

				stop(udpFrontend, httpFrontend, logic, errChan, peerStore)
`

After adding the additional debug lines, it now behaves correctly. odd.
I then tried removing the two debug lines I added above and proceeded to remove the last debug log call in the restart case like so:

`//	log.Debug("Successfully restarted")`

And this also resolved the issue.
So it seams something about there been a call to log.Debug at the end of the case for restart that is causing other cases to run?

I'm using go1.8.1

**Comment by mrd0ll4r** [comment]
That's very weird, what system are you on and how did you send the signal?

**Comment by TheOriginalWinCat** [comment]
I'm on Ubuntu 16.04.2 LTS x64
I sent the signal with 

> kill -SIGUSR1 id
