### ISSUE TITLE
Chihaya as a library

### ISSUE THREAD

**Issue by pushrax** [chihaya/chihaya#320]
It should be possible to implement your own middleware and plug it into Chihaya without forking the repo. This mainly comes down to config parsing.

**Comment by mrd0ll4r** [comment]
Are you thinking of the go plugin system? Otherwise I can't think of a way to get the middleware running without modifying the chihaya source at some point.

**Comment by jzelinskie** [comment]
The other option is parsing the config as bytes and just passing that along to the middleware and having it actually parse it into the proper config. I've done this trick in a few projects before.

**Comment by mrd0ll4r** [comment]
But that still doesn't solve the problem of how to plug own middleware into chihaya, does it? Still need to compile that in?

**Comment by jzelinskie** [comment]
Sure, but you can basically just fork the main package and only have to maintain that.
The Go plugin system only works on Linux atm and we already have FreeBSD users, so that's not a viable solution.

**Comment by mrd0ll4r** [comment]
I gotta admit I don't quite see the problem yet... We can just reintroduce the registration pattern for middleware and it should (apart from adding a few imports) work as @pushrax expects it to?

**Comment by pushrax** [comment]
Yes, the registration system is what I'm looking for. The issue comes from the hardcoded config parsing in [CreateHooks](https://github.com/chihaya/chihaya/blob/ceacd6bdbd7a7013e07ff086227ed7bc41e9d408/cmd/chihaya/config.go#L56). Passing the byte slice into the config seems a reasonable enough solution.

**Comment by jzelinskie** [comment]
I've got step 1 of this merged which is the registration for storage, I'm going to work on the middleware next. We originally didn't have this because I felt like it was making a lot of boilerplate for middleware, but I agree the hardcoding is quite nasty.
