### ISSUE TITLE
CentOS 7 RPM package and versioning

### ISSUE THREAD

**Issue by elico** [chihaya/chihaya#321]
I want to publich a RPM package of chihaya for CentOS 7 and couple other RPM based systems.
I can automate the process but I am missing some sort of versioning.
Like what is stable now and what was stable in the past?
Currently I want to build 3 version:
- old 1(was stabe)
- new 2 (basically stable)
- tip 2(beta)

I will need the git revisions for each and everyone of these so I would be able to buid them.
Thanks,
Eliezer

**Comment by mrd0ll4r** [comment]
Hey,

v1: https://github.com/chihaya/chihaya/tree/release-v1.0 (you should check out the branch rather than a specific git commit, we push bugfixes to the branch). We have tags for the patches, [see here](https://github.com/chihaya/chihaya/tags), if that helps.

about v2: This is gonna be more tricky.
We have a release candidate [v2.0.0-rc1](https://github.com/chihaya/chihaya/releases/tag/v2.0.0-rc.1), but that's pretty old. (@jzelinskie maybe we should cut another RC)
We'll continue cutting release candidates until we're satisfied with the rewrite. I can't give you an estimate on when this is gonna be, we're just writing this in our free time.
Point is: At some point we're gonna drop the `-rc.#` and continue with semantic versioning. I don't know how RPMs are versioned, so no idea if that's gonna be a problem for you.

Generally @jzelinskie is more of an expert on versioning and deployment than I am, sorry :)

**Comment by elico** [comment]
@mrd0ll4r It's ok for now.
I will start with v1.0 and I will use my own RPM revisions with a special note in the RPM changelog that will describe what exact version it will be.
I will look at the v1.0 tree and I will probably have more questions about what should be the optimal default configuration so I am keeping this issue open until I will clear more things out and will wait for @jzelinskie for more feedback.

**Comment by elico** [comment]
OK the RPM is ready:
http://ngtech.co.il/repo/centos/7/x86_64/chihaya-1.0.2-2.el7.centos.x86_64.rpm
SRPM at:
http://ngtech.co.il/repo/centos/7/SRPMS/chihaya-1.0.2-2.el7.centos.src.rpm

The packages are prebuilt by GoLang 1.8.1.
The next update will be when I will upgrade the GoLang build machine to 1.8.3.
Don't try to look for the build instructions in the SRPM file.... it's only a package for a pre built binary.

**Comment by mrd0ll4r** [comment]
Does it install chihaya as a daemon or something? And what about the config?

**Comment by elico** [comment]
@mrd0ll4r It installes chihaya as a process(foreground) under a systemd service(unit).
You run the commands:

> systemctl enable chihaya
> systemctl start chihaya

and It will start at boot time.
The config file is at /etc/chihaya.json
There is also an environment config file under at: 

> /etc/sysconfig/chihaya

The sysconfig file contains two variables:

> LOGSTDERR=true
> CONFIGFILE=/etc/chihaya.json

And this is it.
If you want to change the config file location or the log status, change it there. If you want to change more things just extend the systemd service file manually at: 

> /lib/systemd/system/chihaya.service

Something you might wan to change\add in the service file is:

> LimitNOFILE=16384

which is the "open files"(ulimit -Sn) limit.
And don't forget to run:

> systemctl daemon-reload

After you change the systemd service file.
By default the service has the config options:

>   "udpListenAddr": ":6881",
>   "httpListenAddr": ":6881",
>   "apiListenAddr": ":6880",

Which will cause that chihaya will listen on all interfaces and ip addresses.
A basic firewalld rules would\should be:

> firewall-cmd --permanent --add-port=6881/tcp
> firewall-cmd --permanent --add-port=6881/udp
> firewall-cmd --reload

All the above is for a public faced server, for a private server it's a while other story.
To get the stats from the service just use curl with the command:

> curl "http://localhost:6880/stats?flatten=1"

**Comment by elico** [comment]
On CentOS 7 the only easy to install and us json prettify  tool I found myself using is the ruby gem

> ppjson

Installation:

> yum install ruby ruby-devel -y
> gem install ppjson

Then run:

> curl http://localhost:6880/stats?flatten=1 | ppjson

**Comment by jzelinskie** [comment]
There's also `jq` for pretty printing JSON.

**Comment by elico** [comment]
@jzelinskie indeed `jq` works great.
It even colors the output.

**Comment by elico** [comment]
@jzelinskie What is the state of the new versions of chihaya?
Can I try to package it?

**Comment by mrd0ll4r** [comment]
@elico we've tagged all the things remaining for a 2.0 release. Can't give you an ETA, but now you can see  how things are going :)

**Comment by elico** [comment]
@mrd0ll4r I will try to create an RPM for the latest 2.0RC when I would have enough time.

**Comment by mrd0ll4r** [comment]
that one is pretty old. You can practice with it if you want, but we should be cutting another RC soon-ish :)

**Comment by elico** [comment]
@mrd0ll4r My issue is with golang fetching a specific tag from a specific repo.
It just pulls master\head and I had trouble with it.
It might take me a a while to figure it out or do it manually :\

**Comment by elico** [comment]
@mrd0ll4r I managed to compile the code eventually at:
http://ngtech.co.il/static/chihaya/chihaya-v2.0-rc2/

But I'm still missing the config file to pack it as an RPM.
Any suggestions?

**Comment by mrd0ll4r** [comment]
Nice work!

Make sure to use [reproducible builds](https://github.com/chihaya/chihaya#reproducible-builds). They work differently for the 2.0-rc2 and the current master, but 2.0 will most probably use `dep` as described in the README :)

**Comment by elico** [comment]
@mrd0ll4r I went fully manuall compilation.
To make it all work I ended up with my golang environment doing something like this:

```
cd ~/local-build
git clone git@github.com:chihaya/chihaya
go get github.com:chihaya/chihaya
cd $GOPATH/src/github.com/chihaya/chihaya
git checkout 2.0.0-rc2
cd -
cd chihaya
git checkout 2.0.0-rc2
cd chihaya/cmd
rsync -av .../old-chihaya-v1-build/Makefile ./
rsync -av .../old-chihaya-v1-build/build.sh ./
rsync -av .../old-chihaya-v1-build/pack.sh ./
make update # to update all dependencies
make all # tries to build binaries for any OS GoLang supports
make pack
scp ..tar.xz server:/...
```
And when the binary was cooked and tested a bit then it's pretty simple to put it into a deb\rpm\other.
The SRPM file is also in the repo ../SRPMS/...

I believe it's pretty simple to use docker to build these binaries but since I'm all manual and I have yet to find a good reason(periodic changes in sources) to make it fully automated.

**Comment by mrd0ll4r** [comment]
What exactly does `make update` do? The builds must use the specified versions of the dependencies, for the v1 build this means using [godep](https://github.com/tools/godep), for the v2 build this will be using [dep](https://github.com/golang/dep).

**Comment by elico** [comment]
@mrd0ll4r technically it should run "go get xyz" for all dependencies.
in this specific build it updates using "go get xyz" all external dependencies.

**Comment by mrd0ll4r** [comment]
That will fetch the latest `master` of those dependencies, meaning that on each rebuild the versions could change. The whole point of reproducible builds is that Chihaya is built with specific versions of all dependecies, so that no matter _when_ someone builds chihaya 2.0 it's always going to produce the same, correct build.

**Comment by elico** [comment]
@mrd0ll4r I am open to suggestions but if the dependencies tends to change their sources in the same rate as chihaya It's really shouldn't be a big issue.
Also If master is considered stable be all the maintainers it's fine for me...

**Comment by jzelinskie** [comment]
If you're packaging something, you should not use `go get` over using our repository's dependency management tool (currently [dep](https://github.com/golang/dep)). We do test against HEAD for all of our dependencies, but cannot guarantee that practice will continue indefinitely into the future. For example, a library could make drastic changes that we cannot adopt.

I'd also be interested upstreaming this process, if you're willing to share it.

**Comment by elico** [comment]
@jzelinskie I can try to understand dep but havn't used it yet.
Any recommendations about ways to learn this option\tool.

**Comment by jzelinskie** [comment]
All you need to know is to run `dep ensure` instead of `go get`.

```sh
$ dep ensure
$ go install github.com/chihaya/chihaya/cmd/chihaya
```

**Comment by elico** [comment]
@jzelinskie and what does dep ensure relies on when picking up the right libraries?

**Comment by jzelinskie** [comment]
It looks at the constraints we write in [Gopkg.toml](https://github.com/chihaya/chihaya/blob/master/Gopkg.toml) and then uses a SAT solver to find compatible versions of all the dependent libraries and saves that into [Gopkg.lock](https://github.com/chihaya/chihaya/blob/master/Gopkg.lock). When a Gopkg.lock file exists, it `dep ensure` populates the vendor directory with the exact versions of all of the libraries in the lockfile.

**Comment by elico** [comment]
@jzelinskie Thanks.
I didn't knew it exists and how it works despite to the fact I noticed posts and articles about vendoing.

**Comment by elico** [comment]
@jzelinskie but there are not gopkg.toml, there are glide.yaml and .lock..

**Comment by jzelinskie** [comment]
Yeah, we used to use glide which does very similar -- you simply need to use `glide install` instead of `dep ensure`.

**Comment by elico** [comment]
@jzelinskie @mrd0ll4r I want to re-package an RPM and was wondering about the state of the current code and tags.

**Comment by mrd0ll4r** [comment]
Hey, sorry for the ultra-late reply. 2.0 is still not out, I'll get to do some work this week or the next week, my plans are to update to the latest go, use go modules, all that jazz... and maybe finally figure out the last issue(s) for 2.0 :)

**Comment by elico** [comment]
@mrd0ll4r I am working on a Dockerised packaging node.
I will use: https://github.com/chihaya/chihaya/blob/master/Dockerfile as a base for my packaging.

**Comment by elico** [comment]
@mrd0ll4r I have created a Dockerised build and packaging for CentOS 7 at:
https://github.com/elico/chihaya-packaging

Notice that the current https://github.com/chihaya/chihaya/blob/master/Dockerfile Doesn't work ...

**Comment by jzelinskie** [comment]
>Notice that the current https://github.com/chihaya/chihaya/blob/master/Dockerfile Doesn't work ...

Can you expand on this?

**Comment by elico** [comment]
> > Notice that the current https://github.com/chihaya/chihaya/blob/master/Dockerfile Doesn't work ...
> 
> Can you expand on this?
<details><summary>Docker build outout</summary><p>

```
[root@centos7-docker chihaya-packaging]# git clone  https://github.com/chihaya/chihaya
Cloning into 'chihaya'...
remote: Enumerating objects: 6497, done.
remote: Total 6497 (delta 0), reused 0 (delta 0), pack-reused 6497
Receiving objects: 100% (6497/6497), 3.31 MiB | 2.95 MiB/s, done.
Resolving deltas: 100% (3619/3619), done.
Checking out files: 100% (90/90), done.
[root@centos7-docker chihaya-packaging]# cd chihaya
[root@centos7-docker chihaya]# ls 
bittorrent  CONTRIBUTING.md  Dockerfile  frontend  go.sum   MAINTAINERS  pkg        storage
cmd         dist             docs        go.mod    LICENSE  middleware   README.md
[root@centos7-docker chihaya]# stat Dockerfile 
  File: ‘Dockerfile’
  Size: 669       	Blocks: 8          IO Block: 131072 regular file
Device: 29h/41d	Inode: 680750      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:nfs_t:s0
Access: 2020-01-07 06:42:17.011981264 +0200
Modify: 2020-01-07 06:42:17.011981264 +0200
Change: 2020-01-07 06:42:17.011981264 +0200
 Birth: -
[root@centos7-docker chihaya]# docker build -t chihaya-latest .
Sending build context to Docker daemon   4.07MB
Step 1/13 : FROM golang:alpine AS build-env
 ---> cb1c8647572c
Step 2/13 : LABEL maintainer "Jimmy Zelinskie <jimmyzelinskie+git@gmail.com>"
 ---> Using cache
 ---> ef21878e9f17
Step 3/13 : RUN apk add --no-cache curl git
 ---> Using cache
 ---> 80f9cfad59c2
Step 4/13 : WORKDIR /go/src/github.com/chihaya/chihaya
 ---> Using cache
 ---> 8fad50f223dd
Step 5/13 : COPY . /go/src/github.com/chihaya/chihaya
 ---> 1ac0e9bf6c7e
Step 6/13 : RUN CGO_ENABLED=0 go install github.com/chihaya/chihaya/cmd/...
 ---> Running in e1066257d05a
middleware/jwt/jwt.go:20:2: cannot find package "github.com/SermoDigital/jose/crypto" in any of:
	/usr/local/go/src/github.com/SermoDigital/jose/crypto (from $GOROOT)
	/go/src/github.com/SermoDigital/jose/crypto (from $GOPATH)
middleware/jwt/jwt.go:21:2: cannot find package "github.com/SermoDigital/jose/jws" in any of:
	/usr/local/go/src/github.com/SermoDigital/jose/jws (from $GOROOT)
	/go/src/github.com/SermoDigital/jose/jws (from $GOPATH)
middleware/jwt/jwt.go:22:2: cannot find package "github.com/SermoDigital/jose/jwt" in any of:
	/usr/local/go/src/github.com/SermoDigital/jose/jwt (from $GOROOT)
	/go/src/github.com/SermoDigital/jose/jwt (from $GOPATH)
cmd/chihaya/e2e.go:8:2: cannot find package "github.com/anacrolix/torrent/tracker" in any of:
	/usr/local/go/src/github.com/anacrolix/torrent/tracker (from $GOROOT)
	/go/src/github.com/anacrolix/torrent/tracker (from $GOPATH)
storage/redis/redis.go:10:2: cannot find package "github.com/go-redsync/redsync" in any of:
	/usr/local/go/src/github.com/go-redsync/redsync (from $GOROOT)
	/go/src/github.com/go-redsync/redsync (from $GOPATH)
storage/redis/peer_store.go:33:2: cannot find package "github.com/gomodule/redigo/redis" in any of:
	/usr/local/go/src/github.com/gomodule/redigo/redis (from $GOROOT)
	/go/src/github.com/gomodule/redigo/redis (from $GOPATH)
frontend/http/frontend.go:13:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
	/usr/local/go/src/github.com/julienschmidt/httprouter (from $GOROOT)
	/go/src/github.com/julienschmidt/httprouter (from $GOPATH)
middleware/jwt/jwt.go:23:2: cannot find package "github.com/mendsley/gojwk" in any of:
	/usr/local/go/src/github.com/mendsley/gojwk (from $GOROOT)
	/go/src/github.com/mendsley/gojwk (from $GOPATH)
frontend/udp/connection_id.go:10:2: cannot find package "github.com/minio/sha256-simd" in any of:
	/usr/local/go/src/github.com/minio/sha256-simd (from $GOROOT)
	/go/src/github.com/minio/sha256-simd (from $GOPATH)
cmd/chihaya/e2e.go:9:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/local/go/src/github.com/pkg/errors (from $GOROOT)
	/go/src/github.com/pkg/errors (from $GOPATH)
frontend/http/prometheus.go:6:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
pkg/log/log.go:9:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
	/go/src/github.com/sirupsen/logrus (from $GOPATH)
cmd/chihaya/e2e.go:10:2: cannot find package "github.com/spf13/cobra" in any of:
	/usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
	/go/src/github.com/spf13/cobra (from $GOPATH)
storage/storage_tests.go:7:2: cannot find package "github.com/stretchr/testify/require" in any of:
	/usr/local/go/src/github.com/stretchr/testify/require (from $GOROOT)
	/go/src/github.com/stretchr/testify/require (from $GOPATH)
middleware/middleware.go:9:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
	/go/src/gopkg.in/yaml.v2 (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=0 go install github.com/chihaya/chihaya/cmd/...' returned a non-zero code: 1
```
</p></details>

Take a peek at my working example:
https://github.com/elico/chihaya-packaging/blob/master/alpine-build/Dockerfile#L1

**Comment by jzelinskie** [comment]
This looks like you might have an old version of golang-alpine cached in the Docker CAS.

<details>

```
~/O/g/chihaya ❯❯❯ caffeinate -i docker build -t quay.io/jzelinskie/chihaya-test .
Sending build context to Docker daemon  24.19MB
Step 1/13 : FROM golang:alpine AS build-env
alpine: Pulling from library/golang
e6b0cf9c0882: Pull complete
2848faf0eed1: Pull complete
0f37312ad70f: Pull complete
5788d62ee057: Pull complete
0e6b1d234666: Pull complete
Digest: sha256:0991060a1447cf648bab7f6bb60335d1243930e38420bee8fec3db1267b84cfa
Status: Downloaded newer image for golang:alpine
 ---> 57ce7b9daa9b
Step 2/13 : LABEL maintainer "Jimmy Zelinskie <jimmyzelinskie+git@gmail.com>"
 ---> Running in 07faed6f0d8b
Removing intermediate container 07faed6f0d8b
 ---> 2dd45a5f2eb8
Step 3/13 : RUN apk add --no-cache curl git
 ---> Running in a11844cec405
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/6) Installing nghttp2-libs (1.40.0-r0)
(2/6) Installing libcurl (7.67.0-r0)
(3/6) Installing curl (7.67.0-r0)
(4/6) Installing expat (2.2.9-r1)
(5/6) Installing pcre2 (10.34-r1)
(6/6) Installing git (2.24.1-r0)
Executing busybox-1.31.1-r8.trigger
OK: 22 MiB in 21 packages
Removing intermediate container a11844cec405
 ---> 5dafe104c050
Step 4/13 : WORKDIR /go/src/github.com/chihaya/chihaya
 ---> Running in 80007ef045f1
Removing intermediate container 80007ef045f1
 ---> 046e3efdd9cd
Step 5/13 : COPY . /go/src/github.com/chihaya/chihaya
 ---> d36673e41a59
Step 6/13 : RUN CGO_ENABLED=0 go install github.com/chihaya/chihaya/cmd/...
 ---> Running in 454e51ca61ea
go: downloading github.com/anacrolix/torrent v1.0.0
go: downloading github.com/stretchr/testify v1.3.0
go: downloading github.com/prometheus/client_golang v0.9.2
go: downloading gopkg.in/yaml.v2 v2.2.2
go: downloading github.com/SermoDigital/jose v0.0.0-20180104203859-803625baeddc
go: downloading github.com/spf13/cobra v0.0.3
go: downloading github.com/julienschmidt/httprouter v1.2.0
go: downloading github.com/pkg/errors v0.8.1
go: extracting gopkg.in/yaml.v2 v2.2.2
go: extracting github.com/stretchr/testify v1.3.0
go: downloading github.com/minio/sha256-simd v0.0.0-20190131020904-2d45a736cd16
go: extracting github.com/SermoDigital/jose v0.0.0-20180104203859-803625baeddc
go: extracting github.com/prometheus/client_golang v0.9.2
go: downloading github.com/go-redsync/redsync v1.1.1
go: downloading github.com/sirupsen/logrus v1.3.0
go: extracting github.com/minio/sha256-simd v0.0.0-20190131020904-2d45a736cd16
go: extracting github.com/go-redsync/redsync v1.1.1
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: extracting github.com/julienschmidt/httprouter v1.2.0
go: downloading github.com/mendsley/gojwk v0.0.0-20141217222730-4d5ec6e58103
go: downloading github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: downloading github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: extracting github.com/sirupsen/logrus v1.3.0
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: extracting github.com/spf13/cobra v0.0.3
go: downloading github.com/golang/protobuf v1.2.0
go: extracting github.com/anacrolix/torrent v1.0.0
go: extracting github.com/mendsley/gojwk v0.0.0-20141217222730-4d5ec6e58103
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: extracting github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: extracting github.com/davecgh/go-spew v1.1.1
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: extracting github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/golang/protobuf v1.2.0
go: extracting github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
go: extracting github.com/spf13/pflag v1.0.3
go: downloading github.com/anacrolix/dht v0.0.0-20181129074040-b09db78595aa
go: downloading github.com/anacrolix/missinggo v0.0.0-20181129073415-3237bf955fed
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/pmezard/go-difflib v1.0.0
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/anacrolix/dht v0.0.0-20181129074040-b09db78595aa
go: extracting github.com/anacrolix/missinggo v0.0.0-20181129073415-3237bf955fed
go: extracting golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
go: downloading github.com/huandu/xstrings v1.0.0
go: downloading github.com/bradfitz/iter v0.0.0-20140124041915-454541ec3da2
go: extracting github.com/huandu/xstrings v1.0.0
go: extracting github.com/bradfitz/iter v0.0.0-20140124041915-454541ec3da2
go: downloading golang.org/x/sys v0.0.0-20190204203706-41f3e6584952
go: extracting golang.org/x/sys v0.0.0-20190204203706-41f3e6584952
go: finding github.com/anacrolix/torrent v1.0.0
go: finding github.com/sirupsen/logrus v1.3.0
go: finding github.com/julienschmidt/httprouter v1.2.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/anacrolix/dht v0.0.0-20181129074040-b09db78595aa
go: finding github.com/prometheus/client_golang v0.9.2
go: finding github.com/SermoDigital/jose v0.0.0-20180104203859-803625baeddc
go: finding github.com/anacrolix/missinggo v0.0.0-20181129073415-3237bf955fed
go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/minio/sha256-simd v0.0.0-20190131020904-2d45a736cd16
go: finding github.com/spf13/cobra v0.0.3
go: finding github.com/stretchr/testify v1.3.0
go: finding golang.org/x/sys v0.0.0-20190204203706-41f3e6584952
go: finding github.com/mendsley/gojwk v0.0.0-20141217222730-4d5ec6e58103
go: finding github.com/spf13/pflag v1.0.3
go: finding github.com/bradfitz/iter v0.0.0-20140124041915-454541ec3da2
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/go-redsync/redsync v1.1.1
go: finding github.com/golang/protobuf v1.2.0
go: finding github.com/gomodule/redigo v2.0.0+incompatible
go: finding github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910
go: finding github.com/prometheus/common v0.0.0-20181126121408-4724e9255275
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/huandu/xstrings v1.0.0
go: finding github.com/prometheus/procfs v0.0.0-20181204211112-1dc9a6cbc91a
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
Removing intermediate container 454e51ca61ea
 ---> 2df920ac5752
Step 7/13 : FROM alpine:latest
latest: Pulling from library/alpine
e6b0cf9c0882: Already exists
Digest: sha256:2171658620155679240babee0a7714f6509fae66898db422ad803b951257db78
Status: Downloaded newer image for alpine:latest
 ---> cc0abc535e36
Step 8/13 : RUN apk add --no-cache ca-certificates
 ---> Running in 82e13ac59047
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20191127-r0)
Executing busybox-1.31.1-r8.trigger
Executing ca-certificates-20191127-r0.trigger
OK: 6 MiB in 15 packages
Removing intermediate container 82e13ac59047
 ---> 41374630dea5
Step 9/13 : COPY --from=build-env /go/bin/chihaya /chihaya
 ---> f09e1884d3be
Step 10/13 : RUN adduser -D chihaya
 ---> Running in 5ac3594764f7
Removing intermediate container 5ac3594764f7
 ---> 64a776dceff2
Step 11/13 : EXPOSE 6880 6969
 ---> Running in e53b2eb7533a
Removing intermediate container e53b2eb7533a
 ---> 8ccba27d9ef5
Step 12/13 : USER chihaya
 ---> Running in 521145c8ea67
Removing intermediate container 521145c8ea67
 ---> 2311796bb030
Step 13/13 : ENTRYPOINT ["/chihaya"]
 ---> Running in 94aeb6ad7102
Removing intermediate container 94aeb6ad7102
 ---> 60c55ec5fe32
Successfully built 60c55ec5fe32
Successfully tagged quay.io/jzelinskie/chihaya-test:latest
```

</details>


Also, have you considered making your packaging repository a [copr repository](https://copr.fedorainfracloud.org/)?

**Comment by elico** [comment]
> This looks like you might have an old version of golang-alpine cached in the Docker CAS.
> 
> Also, have you considered making your packaging repository a [copr repository](https://copr.fedorainfracloud.org/)?

Well you seem to be right the second time about this subject..
About the copr, do you have any start points?

**Comment by elico** [comment]
@jzelinskie This seems to work:
https://copr-be.cloud.fedoraproject.org/results/elicro/Chihaya/epel-7-x86_64/01142050-chihaya/

**Comment by mrd0ll4r** [comment]
Sorry I didn't chime in earlier, @jzelinskie is the expert on all things docker anyway :) I'm a bit busy atm unfortunately, but should get better at some point in the future.
