### ISSUE TITLE
Support BEP31 AKA "Retry In" field for Client Errors

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#327]
[This BEP](http://www.bittorrent.org/beps/bep_0031.html) describes how to control the exponential back-off usually present in BitTorrent clients after they receive an error from the tracker.

**Comment by mrd0ll4r** [comment]
This is HTTP-ony, right? What would we set it to?

**Comment by jzelinskie** [comment]
We could make ClientErrors a struct with two fields and use reason depending on the error.

**Comment by mrd0ll4r** [comment]
Sounds good

**Comment by jzelinskie** [comment]
It doesn't look like libtorrent implements this and we don't really have a good idea of how to come up with values to tell clients to wait.

I'll close this for now, unless someone can come up with a good argument for it.
