### ISSUE TITLE
Replace prand package with xorshift

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#328]
* [Potential library](https://github.com/lazybeaver/xorshift)
* [Wikipedia article](https://en.wikipedia.org/wiki/Xorshift)

We could also use a port of the [RNG used in Mario Kart 64](https://gist.github.com/jzelinskie/af9a119e697c3c8a0dae3e388d60310b) lol

**Comment by mrd0ll4r** [comment]
We could test [c2goasm](https://github.com/minio/c2goasm) on this :) But the library looks pretty fast already.
The library is quite handy, it [exports the necessary structs](https://github.com/lazybeaver/xorshift/blob/master/xorshift64star.go#L3), so we could pool them too.
