### ISSUE TITLE
Milestones / Information for new contributors

### ISSUE THREAD

**Issue by fijam** [chihaya/chihaya#36]
The Chihaya project has been recently mentioned on [/r/trackers](http://www.reddit.com/r/trackers/comments/2tvi5b/ocelot_10_released/), yet it remains relatively unknown, with Ocelot reigning supreme. 

Since competition drives innovation and improvement, perhaps a list of milestones or 'low-hanging-fruit' could be written to help potential new contributors see where the project currently stands and where contributions would be most welcome.

**Comment by cooperlees** [comment]
That tracker lost me at “IPv4” only …

Cooper

**Comment by jzelinskie** [comment]
I agree. I think we could be more visual with our process via GH issues. In the past, we've mostly just discussed things on IRC. I still do recommend anyone interested to come on IRC as everyone idles there.

**Comment by jzelinskie** [comment]
I'm going to close this now that we have lots of labels in GitHub. Now that things are more stable, we can document more low hanging fruit.
