### ISSUE TITLE
UDP frontend should cache time.Now()

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#360]
https://github.com/chihaya/chihaya/blob/master/frontend/udp/frontend.go#L259
https://github.com/chihaya/chihaya/blob/master/frontend/udp/frontend.go#L275

Every packet triggers a call to `time.Now()` - we should cache that the same way we do in the storage, seee [here](https://github.com/chihaya/chihaya/blob/master/storage/memory/peer_store.go#L149-L163).

**Comment by jzelinskie** [comment]
This should get refactored into a library.
