### ISSUE TITLE
/health endpoint

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#37]
Should we include a /health endpoint that attempts to ping the backend?

**Comment by cooperlees** [comment]
You could do that with /check if enabled and running in private mode ... People could also overload it to check more ... E.g. Log into DB.

Cooper

**Comment by jzelinskie** [comment]
I like that idea. Should we add a "ping" method to the backend.Conn interface that we call in in /check if private is enabled?

**Comment by pushrax** [comment]
:+1: for a single endpoint. That implementation sounds reasonable @jzelinskie
