### ISSUE TITLE
[Feature]: Black/White List

### ISSUE THREAD

**Issue by aboanas93** [chihaya/chihaya#375]
**Blacklist Mode** 
 Block one or more torrent files identified by something unique (e.g. _infohash_) from being tracked by the server for different reasons (e.g. illegal content) and this list can be stored anywhere (e.g DB/TXT).

**Whitelist Mode** 
 Allow one or more torrent files identified by something unique  (e.g. _infohash_) to be tracked by the server for different reason (e.g. private tracker) and this list can be stored anywhere (e.g DB/TXT).

**Dual Mode** 
 Allow all and when needed block one or more torrent files identified by something unique (e.g. _infohash_) and this list can be stored anywhere (e.g DB/TXT).

PS: the first two modes are inspired by opentracker, unfortunately it can't be activated simultaneously (Dual Mode) in it, and the tracker needs to be restarted everytime the list changed.

**Comment by mrd0ll4r** [comment]
Hey @aboanas93, thx for the issue.

I don't see how the Dual Mode is different from the Blacklist Mode yet?

**Comment by aboanas93** [comment]
Weird, as I read it now again it makes no sense, sorry.
Please ignore the Dual Mode, yet the list updating mechanism is still an issue.

**Comment by mrd0ll4r** [comment]
Alright. We had this at some point, but it got lost along the rewrite.

The easiest way to implement this would be like the client approval middleware (that one checks if the client ID is whitelistet/blacklistet). It's configured [like this](https://github.com/chihaya/chihaya/blob/master/example_config.yaml#L130-L135), and implemented [like this](https://github.com/chihaya/chihaya/blob/master/middleware/clientapproval/clientapproval.go).

As you can see, the whitelist/blacklist entries are just stored in the configuration file. This is literally the most simple approach, and it works with your requirements. You don't have to restart the tracker, you can reload the configuration with SIGUSR1 on unix. This will shut down and restart everything except the storage, so nothing of value is lost :)

Someone at deibel.rip already took a shot at this, see [here](https://git.decibel.rip/X/chihaya/src/master/middleware/torrentapproval/torrentapproval.go), HOWEVER take the implementation with a grain of salt. For example, they're missing an `RWMutex` around the `torrents` map.

Do you want to take a shot at programming this? Would be a good way to get into open source programming, and it shouldn't be too hard :)

**Comment by aboanas93** [comment]
Even though I can read code and understand quite-enough portion of it, I still can't write code from ground up, just trial/error editing (will try it).
That being said, this implementation would do for the current time and I hope one day I would create a pull request.
