### ISSUE TITLE
Move default port to 6969

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#386]
Apparently 6881 is actually the default port for the p2p bittorrent protocol, whereas the tracker port is supposed to be 6969.

source: https://wiki.wireshark.org/BitTorrent#Protocol_dependencies

**Comment by elico** [comment]
@jzelinskie needs to be changed in the example yaml.

**Comment by mrd0ll4r** [comment]
@elico want to send a PR?

**Comment by elico** [comment]
@mrd0ll4r Since it's configurable I will just apply it to my RPM\deb sources.
