### ISSUE TITLE
Chihaya can achieve high availability by using redis storage backend.

### ISSUE THREAD

**Issue by duyanghao** [chihaya/chihaya#387]
@jzelinskie @pushrax @mrd0ll4r  I have done some works for HA of Chihaya, if your guys have an interest on this topic, have a look at [this](https://github.com/duyanghao/chihaya/tree/redis-dev).

**Comment by mrd0ll4r** [comment]
Hey @duyanghao,

that's pretty cool! We had a few people taking a shot at redis but nothing ever got completed or merged.
Does your implementation pass the automated tests in [storage/storage_tests.go](https://github.com/chihaya/chihaya/blob/master/storage/storage_tests.go) ?

**Comment by duyanghao** [comment]
@mrd0ll4r I am afraid not, as you can see,[my redis work](https://github.com/duyanghao/chihaya/commits/redis-dev) is based on [this commit](https://github.com/duyanghao/chihaya/commit/9c9b4a50029c018d281b030af736454db97275fd) instead of the latest master branch.

but I have tests for redis storage backend and show successfully!

There are some adjustments to be done before merged to master. 

And that why I have not created a pr : )

**Comment by mrd0ll4r** [comment]
Yes, you'd have to rebase off master for sure. Also you'd have to register the redis implementation the same way the `memory` implementation is registered now.

So... if you want, go for it :) Rebase, add the tests, clean it all up a bit and open a PR. There's definitely demand for a redis implementation of the storage!

Also, we recommend updating your production environment to a more recent commit :D But that comes with rebasing and eventually merging into master.

**Comment by pushrax** [comment]
@duyanghao cool work! What is your production use-case of Chihaya?

**Comment by duyanghao** [comment]
@pushrax Actually, we use Chihaya as Tracker of P2P based Docker Registry.

**Comment by duyanghao** [comment]
@mrd0ll4r Done for [this PR](https://github.com/chihaya/chihaya/pull/389).

**Comment by jzelinskie** [comment]
@duyanghao do you have any more public details on your p2p docker registry? Quay.io uses Chihaya for p2p distribution from a centralized Docker registry. Is that also what you do or are you actually decentralizing the registry as well?

**Comment by mrd0ll4r** [comment]
This has been merged to master in #433 :) Closing.
