### ISSUE TITLE
Rewrite paths with godep

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#39]
When we vendored our dependencies with `godep`, we didn't use `godep save -r` which will rewrite imports in all of the source files to very specifically only use the libraries in the godep workspace.

**Comment by pushrax** [comment]
I don't totally agree with this, is there a particularly compelling reason to do so?

**Comment by jzelinskie** [comment]
We do it at CoreOS for all of our projects (checkout how [etcd](https://github.com/coreos/etcd) looks).
Basically, it lets the project vendor their dependencies and still be go-get-able.
In our current situation, a dependency could break their master branch and anyone naively running the normal `go install` will just have a broken build. This would also include anyone using chihaya as a library (adding their own drivers and using `chihaya.Boot`). If we use `godep save -r`, anyone dependent on the project will use our vendored libraries without any extra effort

**Comment by jzelinskie** [comment]
Yeah, we decided against this.
