### ISSUE TITLE
chihaya.rule  FAILED: [yaml: line 19: did not find expected <document start>]

### ISSUE THREAD

**Issue by xjtdy888** [chihaya/chihaya#397]
Thanks first to all developers。

I add the config to prometheus but has a problem。
I don't know how to solve it

./promtool check config prometheus.yml 
Checking prometheus.yml
  SUCCESS: 1 rule files found

Checking chihaya.rules
  FAILED: [yaml: line 19: did not find expected <document start>]
![default](https://user-images.githubusercontent.com/622685/38303292-3476abe0-3838-11e8-8745-74293088a23d.png)

**Comment by xjtdy888** [comment]
@mrd0ll4r 
Thanks for replay.
my  prometheus version information
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2

**Comment by xjtdy888** [comment]
./promtool check config prometheus.yml 
Checking prometheus.yml
  SUCCESS: 1 rule files found

Checking chihaya.rules
  FAILED: [yaml: line 19: did not find expected <document start>]

**Comment by mrd0ll4r** [comment]
I will look into this eventually, but I'm on vacation for now, sorry :)

**Comment by jzelinskie** [comment]
Prometheus changed the rules format to YAML for v2.0. promtool has a command for converting them, but that still fails. I'm going to follow up on this.
