### ISSUE TITLE
not an Issue / more of help 

### ISSUE THREAD

**Issue by hi5kba** [chihaya/chihaya#398]
While Not an Issue... it'd help me a great deal.
Im currently trying to create a custom torrent tracker (Front & Backend), for my website. i however have no Idea where to begin coding wise  or whats involved.

 i haved worked on Projects involving PHP and i Know my way around MySQL and other such databases.
and this is something that i want to say "i built that".

i have plenty of time to learn the basics from the ground up. even if it's just creating a basic announce before adding on to it.

i have tried Various searches Via Google and Bing. but couldn't find anything usefull in regards to what i want to do.

if could take a minute or so of your time to provide a list resource(s) or stuff I need to read it'll be very much appreciated. ill either check here or you can snap me link on via google+ 
either way ill know as soon as this is either closed or removed.

thanks for your time

**Comment by pushrax** [comment]
https://wiki.theory.org/index.php/BitTorrentSpecification#Tracker_HTTP.2FHTTPS_Protocol has a good overview of the protocol.
