### ISSUE TITLE
master build failing

### ISSUE THREAD

**Issue by mdkozlowski** [chihaya/chihaya#402]
Following the instructions in [reproducible builds](https://github.com/chihaya/chihaya#reproducible-builds) results in the following errors when `go install` is run on ff15955dcce95d296aae5ec667de867a87d4506c

`# github.com/chihaya/chihaya/vendor/github.com/anacrolix/dht/krpc
vendor\github.com\anacrolix\dht\krpc\CompactIPv4NodeInfo.go:21:28: undefined: slices.Map
vendor\github.com\anacrolix\dht\krpc\CompactIPv6NodeAddrs.go:10:28: undefined: slices.Map
vendor\github.com\anacrolix\dht\krpc\CompactIPv6NodeInfo.go:16:28: undefined: slices.Map`

Go version: 1.9.2

**Comment by jzelinskie** [comment]
We don't have the dependencies for the chihaya-e2e test tool included in our deps.

Let's just vendor it and call it a day.
