### ISSUE TITLE
tls1.3  ?

### ISSUE THREAD

**Issue by f4nff** [chihaya/chihaya#409]
https://github.com/cloudflare/tls-tris
Request support for tls1.3

**Comment by mrd0ll4r** [comment]
> THE API IS NOT STABLE AND DOCUMENTATION IS NOT GUARANTEED.

and

> So, to build with tls-tris, you need to use a custom GOROOT.

are two reasons why this is definitely not happening.

What is your use case? What features of TLS 1.3 over TLS 1.2 do you need?

**Comment by elico** [comment]
@mrd0ll4r I really do not see why there is a rush towards TLS 1.3?
If it works with TLS 1.2 it should be secure for at-least the next 2 years as far as I understand.

**Comment by pushrax** [comment]
Yeah, we can just wait until Go supports it natively I think.

**Comment by f4nff** [comment]
https://github.com/cloudflare/tls-tris      tls1.3 golang～

**Comment by mrd0ll4r** [comment]
@f4nff I gave you a detailed answer why we are not doing that. Please read the replies I write.

@elico I agree.

**Comment by mrd0ll4r** [comment]
TLS 1.3 will be enabled by default in Go 1.13. In Go 1.12 it can be enabled experimentally. See the [preliminary release notes](https://tip.golang.org/doc/go1.12#tls_1_3).

**Comment by mrd0ll4r** [comment]
TLS 1.3 is now enabled [by default in Go 1.13](https://golang.org/doc/go1.13#tls_1_3).
