### ISSUE TITLE
http: Make connection closing behaviour configurable

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#411]
For now, we force connections to be closed after each request ([see here](https://github.com/chihaya/chihaya/blob/master/frontend/http/frontend.go#L164)) for obvious reasons. However, because reverse-proxying is a pretty common thing, we should make this configurable and document why one should enable/disable it.

EDIT: It might be especially nice to reverse-proxy an HTTPS Chihaya and use HTTP 2, we should maybe test this and then document whatever happened :)

**Comment by f4nff** [comment]
good
