### ISSUE TITLE
Real IP http header ignore case sensitivity

### ISSUE THREAD

**Issue by yashpal1995** [chihaya/chihaya#428]
In order to get the IP address of a client, when using some reverse proxy or load balancer, one can use `real_ip_header` config defined in http section. As http headers are [case insensitive](https://tools.ietf.org/html/rfc2616#section-4.2), was there any reason to not canonicalize header key?

Let me know if I should create a PR to apply following fix.

```diff
diff --git a/frontend/http/parser.go b/frontend/http/parser.go
index 870b0d3..d5e4644 100644
--- a/frontend/http/parser.go
+++ b/frontend/http/parser.go
@@ -153,8 +153,8 @@ func requestedIP(r *http.Request, p bittorrent.Params, opts ParseOptions) (ip ne
 	}
 
 	if opts.RealIPHeader != "" {
-		if ips, ok := r.Header[opts.RealIPHeader]; ok && len(ips) > 0 {
-			return net.ParseIP(ips[0]), false
+		if ip := r.Header.Get(opts.RealIPHeader); ip != "" {
+			return net.ParseIP(ip), false
 		}
 	}
 

```

**Comment by elico** [comment]
@yashpal1995 I am not sure but there is one issue I might see.
If there are couple multiple proxies on the path to the service then the frontend proxy like nginx would need to cleanup the header and re-set it.

I am pretty sure that if there are more then 1 ip addresses in this header this parsing function will not work as expected.
I have yet to see this function code but I believe that if for any reason the service is exposed to a network with a frontend service and also to a local/internal network then it should have a basic acl to which source addresses this header parsing will be done or allowed.

@jzelinskie what do you think?

**Comment by pushrax** [comment]
> was there any reason to not canonicalize header key

No, feel free to send in a PR. Patch looks good; the behaviour is identical other than the canonicalization. Maybe could be worth caching the canonicalized string (CanonicalMIMEHeaderKey), I'm not up to speed with the target level of optimization at this point to answer that.

**Comment by yashpal1995** [comment]
Hi @pushrax, I've created a PR containing above patch. After going through the implementation of `CanonicalMIMEHeaderKey`, I feel like having a cache of the canonicalized string would be overkill with very little optimization.

**Comment by mrd0ll4r** [comment]
We could just sanitize the config value for `RealIPHeader` with `CanonicalMIMEHeaderKey`, no? And then keep the current lookup code.

**Comment by yashpal1995** [comment]
@mrd0ll4r maybe at [config validation](https://github.com/chihaya/chihaya/blob/3f9ac795701cf8cdafafa0641a20fe49d6cd89f4/frontend/http/frontend.go#L69), but seems like premature optimization, and I find above change more intuitive like without knowing the inner impl of `header.Get` func with minor overhead of I guess 1 alloc. Anyways, I don't have any strong preference of one over other. Let me know if should change it.

**Comment by mrd0ll4r** [comment]
That's a good point! Do it your way :)
