### ISSUE TITLE
./main.go:270:10: undefined: EndToEndRunCmdFunc

### ISSUE THREAD

**Issue by f4nff** [chihaya/chihaya#432]
`./main.go:270:10: undefined: EndToEndRunCmdFunc`

```
./e2e.go:94:3: unknown field 'HttpClient' in struct literal of type tracker.Announce
./e2e.go:122:3: unknown field 'HttpClient' in struct literal of type tracker.Announce
```

bug～!

**Comment by f4nff** [comment]
`go get github.com/chihaya/chihaya` , can't compile！
go version 1.11.1

**Comment by f4nff** [comment]
```
go get github.com/chihaya/chihaya

go get github.com/SermoDigital/jose/crypto

go get github.com/SermoDigital/jose/jws

go get github.com/SermoDigital/jose/jwt

go get github.com/anacrolix/torrent/tracker

go get github.com/julienschmidt/httprouter

go get github.com/mendsley/gojwk

go get github.com/minio/sha256-simd

go get github.com/pkg/errors

go get github.com/prometheus/client_golang/prometheus

go get github.com/sirupsen/logrus

go get github.com/spf13/cobra

go get github.com/stretchr/testify/require

go get gopkg.in/yaml.v2

```

```
./e2e.go:94:3: unknown field 'HttpClient' in struct literal of type tracker.Announce
./e2e.go:122:3: unknown field 'HttpClient' in struct literal of type tracker.Announce
```

**Comment by f4nff** [comment]
After testing, `github.com/anacrolix/torrent/tracker` has been updated, the project has no way to compile successfully.

**Comment by f4nff** [comment]
sorry~

**Comment by mrd0ll4r** [comment]
Did you try building with `dep`, as described in https://github.com/chihaya/chihaya#reproducible-builds? That should pin the version of each dependency so that everything builds :)

**Comment by f4nff** [comment]
`github.com/anacrolix/torrent/tracker`
After the update, chihaya can't be compiled.

**Comment by mrd0ll4r** [comment]
Did you try building with `dep`, as described in the README?

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/48293755-8b300f00-e4bb-11e8-88d2-a9fd739b3f67.png)

**Comment by mrd0ll4r** [comment]
**Use `dep` as described in the README.**
