### ISSUE TITLE
Update dependency: anacrolix/torrent

### ISSUE THREAD

**Issue by onestraw** [chihaya/chihaya#444]
The latest [`Announce`](https://github.com/anacrolix/torrent/blob/master/tracker/tracker.go#L53) struct has discarded `HttpClient` field.

```
cmd/chihaya/e2e.go:94:3: unknown field 'HttpClient' in struct literal of type tracker.Announce
cmd/chihaya/e2e.go:122:3: unknown field 'HttpClient' in struct literal of type tracker.Announce
```
https://travis-ci.org/chihaya/chihaya/jobs/474766594

**Comment by mrd0ll4r** [comment]
IIRC we had a very similar issue with anacrolix/torrent lately, so we started vendoring it. I now see that we didn't pin it to a specific commit, just to `master`. Can you figure out a sensible commit to pin this to and do that? This is coming up too often...

**Comment by anacrolix** [comment]
I've released 1.0.0, to address versioning problems. Feel free to create issues if something goes awry. Cheers

**Comment by mrd0ll4r** [comment]
Hey @anacrolix, thank you so much! That's really nice :)

In that case, @onestraw could you please update our vendored packages with a version for this?

**Comment by onestraw** [comment]
@mrd0ll4r Sure, we should first update the torrent package to the latest and pin it to 1.0.0
