### ISSUE TITLE
Should we export shard details?

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#45]
Should we continue to export [these methods](https://github.com/chihaya/chihaya/blob/54593ff5c2a964b0077b7586d677cb30f7dd12de/tracker/storage.go#L51-L65)?

They seem like an implementation detail to me.

**Comment by pushrax** [comment]
Seems reasonable for those to be private.

**Comment by jzelinskie** [comment]
This was fixed in e02f1dd0ea3e89d9fe8925bf0ad6942e60c1c1ac
