### ISSUE TITLE
The https://github.com/chihaya/chihaya/blob/master/Dockerfile doesn't build

### ISSUE THREAD

**Issue by elico** [chihaya/chihaya#453]
I have tried to run https://github.com/chihaya/chihaya/blob/master/Dockerfile
But it doesn't build.
I want to build a v2 "stable" but I'm not sure about the state of the repo.

**Comment by mrd0ll4r** [comment]
I was just talking with @jzelinskie about releasing 2.0 properly soon. We still have a few things that need to be worked out before, but we're getting there :)

**Comment by jzelinskie** [comment]
Quay auto builds them and hosts them: https://quay.io/repository/jzelinskie/chihaya-git

I'm not sure why you're unable to build them.

**Comment by elico** [comment]
@jzelinskie I want to build them "manually".
In a few hours I will have the "docker build" output.

**Comment by jzelinskie** [comment]
You might have to repull `golang:alpine` because the Dockerfile assumes you're using the most recent version and not an old cached one on your machine.

**Comment by elico** [comment]
@jzelinskie seems to do the trick.
I remembered that there was something awkward about it in the past.
I think that to force a pull by this: https://github.com/moby/moby/issues/13331
you can run  `docker run -i -t  golang:alpine` or somehow validate that the image is the latest.
I wanted this so I can create a docker container that builds for every possible OS and release it as a tar.xz.
What do you think?

**Comment by jzelinskie** [comment]
There are a few existing frameworks to help you do it. I think that's worth creating another issue for. I'm going to close this out.

**Comment by elico** [comment]
@jzelinskie Can you name one?

**Comment by jzelinskie** [comment]
I was looking into this briefly and wanted some time to experiment with https://github.com/karalabe/xgo but haven't yet, so I have no idea if it's any good.

**Comment by elico** [comment]
@jzelinskie I already have this:
http://gogs.ngtech.co.il/NgTech-LTD/golang-build-software-binaries

which works and from I have seen it works with go.mod somehow but not sure.
