### ISSUE TITLE
Config documentation 

### ISSUE THREAD

**Issue by dtrackd** [chihaya/chihaya#48]
Love the project.

I feel it would be much better and easier if you could include either in the READEME or in the github wiki a small paragraph on the each config variable for the tracker.

Explaining its use case and what it means, could save the devs lots of time trying to explain on an individual case by case to new users :)

Edit: would be also good to document the elements in the stats page

**Comment by RCM7** [comment]
Î +1

**Comment by jzelinskie** [comment]
Now that the config is in YAML, we can comment out the example config and make things very easy.

**Comment by Famicoman** [comment]
+1 Would love a breakdown.

**Comment by mrd0ll4r** [comment]
Fixed for v2 in #276
