### ISSUE TITLE
More stats

### ISSUE THREAD

**Issue by dtrackd** [chihaya/chihaya#49]
If possible I would love to see a little more stats information, similar to what the opentracker by erdgeist offers.

Some ideas:
- Top 10/100 Seeded/Leeched torrent hashes
- udp specific stats
- tcp specific stats

Maybe some other stats?

**Comment by jzelinskie** [comment]
We actually don't have a UDP implementation yet, although we aren't coupled to HTTP, it's just a matter of someone implementing the UDP part.

Can you expand on "___ specific stats"?

**Comment by dtrackd** [comment]
by specific stats, I was meaning, the connection counts/peer count/seed count all of that but specific to the protocol. Pretty much same deal as opentracker.

And also on the note, most of the stats on the current system are only for tracker wide. Perhaps people would like to see the growth of IPv6 (and the decline of IPv4) on their tracker as time goes on, so another related small idea is the separation of IPv4/IPv6 stats, just something to think about

**Comment by pushrax** [comment]
IPv4/IPv6 are actually separated. Here's an example from a freshly started instance:

```json
{
  "Started": "2015-02-16T18:30:30.029546608-05:00",
  "Connections.Open": 2,
  "Connections.Accepted": 6,
  "BytesTransmitted": 0,
  "Runtime.GoRoutines": 14,
  "Requests.Handled": 2,
  "Requests.Errored": 0,
  "Requests.Bad": 0,
  "ResponseTime": {
    "P50": 1.560007,
    "P90": 1.560007,
    "P95": 1.560007
  },
  "Tracker.Announces": 0,
  "Tracker.Scrapes": 0,
  "Torrents.Size": 0,
  "Torrents.Added": 0,
  "Torrents.Removed": 0,
  "Torrents.Reaped": 0,
  "Peers.IPv4": {
    "Peers": {
      "Current": 0,
      "Joined": 0,
      "Left": 0,
      "Reaped": 0
    },
    "Seeds": {
      "Current": 0,
      "Joined": 0,
      "Left": 0,
      "Reaped": 0
    },
    "Completed": 0
  },
  "Peers.IPv6": {
    "Peers": {
      "Current": 0,
      "Joined": 0,
      "Left": 0,
      "Reaped": 0
    },
    "Seeds": {
      "Current": 0,
      "Joined": 0,
      "Left": 0,
      "Reaped": 0
    },
    "Completed": 0
  },
  "Memory": {
    "Alloc": 459288,
    "TotalAlloc": 489312,
    "Sys": 3999992,
    "Lookups": 13,
    "Mallocs": 1676,
    "Frees": 445,
    "HeapAlloc": 459288,
    "HeapSys": 1638400,
    "HeapIdle": 794624,
    "HeapInuse": 843776,
    "HeapReleased": 0,
    "HeapObjects": 1231,
    "PauseTotalNs": 25124136
  }
}
```

**Comment by jzelinskie** [comment]
If we add a few more dimensions to the prometheus metrics in our frontends these could all be dynamically queried.

**Comment by mrd0ll4r** [comment]
But we'd have to incorporate prometheus into the storage to get things like most active infohashes, right? Or do you want to log them on the frontends?

**Comment by jzelinskie** [comment]
We can log them as another dimension on the frontend, yes.

**Comment by jzelinskie** [comment]
So apparently, I learned that having unique dimensions in time series databases destroys performance. We're going to have to find a reasonable subset and go with that.

**Comment by jzelinskie** [comment]
I'm going to close this for now. We have UDP/TCP specific metrics now and due to the aforementioned performance implications of including infohashes as a dimension in Prometheus, I don't think we'll be adding "top torrents" unless something changes.

Feel free to open another issue if there's an important metric missing.
