### ISSUE TITLE
Add config to listen on specific address/protcols

### ISSUE THREAD

**Issue by dtrackd** [chihaya/chihaya#51]
I feel it will be good to thing to be able to allow in the config to set the listening addresses and protocol

so something like:

```
"listen_addr" :  {"1.1.1.1",  "[1::2:eeee]", },
"tracker_proto" : "tcp_udp",
```

For example on the ``listen_addr`` you can have if nothing is set just listing to every address and can also specify say ``0.0.0.0`` being all IPv4 or ``[::]`` being all ipv6

For the tracker_proto you can have say ``tcp``, ``udp`` and ``tcp_udp`` which will be both.

**Comment by pushrax** [comment]
`http_listen_addr` is a thing, though supporting multiple addresses and UDP (#53) would be good.

**Comment by dtrackd** [comment]
Opps Sorry about missing ``http_listen_addr``, I thought that it was port. Cheers for the follow up

**Comment by jzelinskie** [comment]
Closing this out. In the refactor branch you could make multiple server instances.
