### ISSUE TITLE
Newbie can't do it run 😅

### ISSUE THREAD

**Issue by FoRTu** [chihaya/chihaya#514]
My idea is to replace my opentracker server with Chihaya.

I try to run the docker version to run some test, but I can't announce any torrent on it. I use the template configure file and the docker image thath apears on the readme.md:

```bash
# Download and edit the example config
curl -L https://raw.githubusercontent.com/chihaya/chihaya/release-v1.0/example_config.json -o config.json
vi config.json

# Run the container with the config file mounted
docker run -p 6880-6882:6880-6882 -v $PWD/config.json:/config.json:ro quay.io/jzelinskie/chihaya:v1.0.1 -v=5
```

It run without any error but when y try to announce a toorrent, the client ncannot conet to the chihaya instance. I have check out the firewall and everithing is right.

I try to get the statistics using HTTP API but I dont know what are the routes and all ai get is a empry response.

Sorry about my ignorance. What I'm doing wrong?

Thank you.

**Comment by mrd0ll4r** [comment]
Hey, this somehow fell under my radar, sorry about that! Did you get it to run? Are you running v1 or master?

**Comment by FoRTu** [comment]
Sorry about closing it.  I was having problems to run the v1 version. After that, today I have try with the master and v2.0.0-rc.1 versions and they works. Now I'm trying to get some metrics from it, without using Prometheus, but I dont know how.

**Comment by mrd0ll4r** [comment]
Nice! If you're using the default config, metrics should be accessible on port 6880 via HTTP. I think the path is either just  `/` or `/metrics`. Let me know how/if that works :)
