### ISSUE TITLE
Stats view IP whitelist

### ISSUE THREAD

**Issue by dtrackd** [chihaya/chihaya#52]
Just an idea.

Implement say a config var for a list of IP address that are allowed to view the stats.

I would assume more tracker admins dont want their users to be able to access these stats.

**Comment by jzelinskie** [comment]
We actually recommend putting something like nginx in front of Chihaya. nginx can handle SSL for you and keep routes private that you don't want exposed.

**Comment by pushrax** [comment]
This would be a nice-to-have though, either via IP whitelist or API key or something.

**Comment by dtrackd** [comment]
Yes nginx in-front of the Chihaya would work for the stats will work wonders. but would it not be better to have the announce/scrapes not go through nginx since another another link in the chain? I am not sure about that part though

**Comment by jzelinskie** [comment]
>and since the stats and the tracker lives on the same URI then we will have to both or non over nginx proxy.

The location directive in nginx will let you specify routes that you want public and ones that you don't.

**Comment by pushrax** [comment]
Though in this case the feature is so small, simple, and obvious that I think it's worth including.

**Comment by jzelinskie** [comment]
I think IP whitelists/blacklists should implemented at the IP layer and not the application layer. Going to draw a line in the sand and say you should use iptables or the like rather then having us add more code that requires persistent storage into chihaya.
