### ISSUE TITLE
UDP support

### ISSUE THREAD

**Issue by pushrax** [chihaya/chihaya#53]
Should be relatively simple to add by implementing a `tracker.Writer` for UDP.

**Comment by jzelinskie** [comment]
http://www.bittorrent.org/beps/bep_0007.html

Leaving this link here as it is relevant for the IPv6 UDP support.

**Comment by jzelinskie** [comment]
...and here's the actual UDP spec
http://www.bittorrent.org/beps/bep_0015.html

**Comment by pushrax** [comment]
UDP support has been merged into `develop`, though there are still probably some issues present. Leaving this open until someone is running UDP in production successfully.

**Comment by jzelinskie** [comment]
This got merged into master
