### ISSUE TITLE
Migrate chat off freenode

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#536]
Lots of drama, my IRC provider also got totally banned from freenode. I think it's time to move on.

There are a few options that I can think of:

- Migrate to something where users don't need something like a bouncer to stay connected (Discord, Matrix)
- Stick with IRC, but move to Libera
- Gitter? I think that got bought by Matrix

**Comment by mrd0ll4r** [comment]
My opinions:

- Discord: I always find this weird, but other open source projects do it too... maybe there's a way where we don't need to make a whole server? Anyway, I have discord and I guess we could use it
- Gitter: Literally never used
- Libera: Works, but I'd bridge that over to Matrix anyway (for the bouncer)
- Matrix: Works I guess

Soo... I'd vote in favor of Matrix or Discord :)

**Comment by jamiew0w** [comment]
i'm just a user but figured i'd give my input as there's probably other people in my position too.

irc + libera please. it's a centralised location where we can easily keep tabs on several projects at once. if it ain't broke...
