### ISSUE TITLE
Panic error when accessing stats

### ISSUE THREAD

**Issue by Power2All** [chihaya/chihaya#54]
Trying this tracker out for the first time to possible replace ocelot.
Sadly, when I access stats, I get a immediate panic error.
IP address in the bottom log is censored.
Here is the full error log:

2015/02/18 12:42:15 http: panic serving x.x.x.x:58379: runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xa8
encoding/json.func·002()
        /usr/local/go/src/encoding/json/encode.go:262 +0x7a
sync/atomic.LoadUint64(0x18632024, 0xf757f338, 0x18632000)
        /usr/local/go/src/sync/atomic/asm_386.s:165 +0xb
github.com/pushrax/faststats.(*Percentile).Value(0x18632000, 0x80522ce, 0x18642950)
        /usr/local/gosrc/src/github.com/pushrax/faststats/percentile.go:47 +0x3a
github.com/pushrax/faststats.(*Percentile).MarshalJSON(0x18632000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/gosrc/src/github.com/pushrax/faststats/json.go:10 +0x50
encoding/json.marshalerEncoder(0x1867a820, 0x829ab00, 0x1863c184, 0xd6, 0x0)
        /usr/local/go/src/encoding/json/encode.go:416 +0xea
encoding/json.(*structEncoder).encode(0x1872e600, 0x1867a820, 0x8291140, 0x1863c184, 0xd9, 0x0)
        /usr/local/go/src/encoding/json/encode.go:584 +0x211
encoding/json.*structEncoder.(encoding/json.encode)·fm(0x1867a820, 0x8291140, 0x1863c184, 0xd9, 0x0)
        /usr/local/go/src/encoding/json/encode.go:598 +0x50
encoding/json.(*structEncoder).encode(0x1872e4c0, 0x1867a820, 0x82ae940, 0x1863c140, 0xd9, 0x18636100)
        /usr/local/go/src/encoding/json/encode.go:584 +0x211
encoding/json.*structEncoder.(encoding/json.encode)·fm(0x1867a820, 0x82ae940, 0x1863c140, 0xd9, 0x1863c100)
        /usr/local/go/src/encoding/json/encode.go:598 +0x50
encoding/json.(*ptrEncoder).encode(0x18730150, 0x1867a820, 0x82a88a0, 0x1863c140, 0x16, 0x0)
        /usr/local/go/src/encoding/json/encode.go:706 +0xc7
encoding/json.*ptrEncoder.(encoding/json.encode)·fm(0x1867a820, 0x82a88a0, 0x1863c140, 0x16, 0x1863c100)
        /usr/local/go/src/encoding/json/encode.go:711 +0x50
encoding/json.(*encodeState).reflectValue(0x1867a820, 0x82a88a0, 0x1863c140, 0x16)
        /usr/local/go/src/encoding/json/encode.go:299 +0x64
encoding/json.(*encodeState).marshal(0x1867a820, 0x82a88a0, 0x1863c140, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:270 +0xb1
encoding/json.(*Encoder).Encode(0x18630940, 0x82a88a0, 0x1863c140, 0x0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:160 +0x6c
github.com/chihaya/chihaya/http.(*Server).stats(0x1861c348, 0xf757f298, 0x18634a80, 0x18634a10, 0x0, 0x0, 0x0, 0x54e47a97, 0x0, 0x0)
        /usr/local/gosrc/src/github.com/chihaya/chihaya/http/routes.go:70 +0x2c0
github.com/chihaya/chihaya/http.*Server.(github.com/chihaya/chihaya/http.stats)·fm(0xf757f298, 0x18634a80, 0x18634a10, 0x0, 0x0, 0x0, 0x840ec20, 0x0, 0x0)
        /usr/local/gosrc/src/github.com/chihaya/chihaya/http/http.go:95 +0x67
github.com/chihaya/chihaya/http.func·001(0xf757f298, 0x18634a80, 0x18634a10, 0x0, 0x0, 0x0)
        /usr/local/gosrc/src/github.com/chihaya/chihaya/http/http.go:38 +0xb5
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0x1860a640, 0xf757f298, 0x18634a80, 0x18634a10)
        /usr/local/gosrc/src/github.com/julienschmidt/httprouter/router.go:298 +0x141
net/http.serverHandler.ServeHTTP(0x186b2080, 0xf757f298, 0x18634a80, 0x18634a10)
        /usr/local/go/src/net/http/server.go:1703 +0x145
net/http.(*conn).serve(0x186483c0)
        /usr/local/go/src/net/http/server.go:1204 +0x9d8
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:1751 +0x2ce

**Comment by jzelinskie** [comment]
Looks like `stats.DefaultStatus` isn't getting initialized. However, it should be getting initialized before the http server ever begins. Can you provide some details on steps to reproduce?

Also, we don't currently have a Gazelle driver yet. If you want to work with us to write one, that'd be great.

**Comment by jzelinskie** [comment]
@pushrax any ideas how https://github.com/pushrax/faststats/blob/0fc2c5e41a187240ffaa09320eea7df9f8071388/percentile.go#L47 is throwing a nil pointer

**Comment by Power2All** [comment]
I just start the server.
Access http://ip.server:6881/stats
Get a message that nothing was send on chrome, and the error is shown in the console.
Using Debian Wheezy with latest GoLang bins and such.
Using right now a modified ocelot (added IP proxy forwarding myself, and some small SQL modifications and torrent auto-load time).
Want to replace it with Chihaya, but sofar with this bug, I got nowhere yet.

**Comment by jzelinskie** [comment]
The version of Go packaged with Debian (1.0.2) is not compatible with Chihaya, which requires 1.3+.

**Comment by Power2All** [comment]
No it's not the debian package i use.
Downloaded latest go version......

**Comment by pushrax** [comment]
Are you using 32-bit or 64-bit Debian? If 64-bit, are you using 64-bit Go?

**Comment by Power2All** [comment]
Good point.
I notice I did the 32bit version.
Trying out with 64bit now, will let you know.

**Comment by Power2All** [comment]
That fixed it pushrax, thanks for pointing out the fail :)
Problem is fixed and can be closed.
