### ISSUE TITLE
Explore using shoco for peer compression

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#541]
If we get a large list of PeerIDs, we can train a model for [shoco](https://pkg.go.dev/github.com/tmthrgd/shoco) that will compress our serialized peer strings more effectively.

**Comment by jzelinskie** [comment]
I tried this and it mostly made the strings grow in size and the few that were smaller were only smaller by 1%.

**Comment by polarathene** [comment]
I'm not familiar with how much of a benefit you'd get from doing so, looking at [a variety of PeerID values from this test](https://github.com/webtorrent/bittorrent-peerid/blob/master/test/basic.js) there doesn't seem like much compressible patterns, beyond some cases of repeated values.

If these are stored as strings, you could probably binary pack the charset directly as a lookup, if the number of valid characters in such a string is less than 128 you could compress these to roughly half the size I think? Or a quarter with a limit of 64 characters. Assuming each character is using 1 byte. Maybe there's a Go package that provides similar functionality.

I don't know how the IDs are used though, might not be worth it if they're frequently accessed and "decompressed" depending on CPU overhead.

Many of those seem to have a 6 character prefix surrounded by `-` on each end (client ID?), that's a little more compressible, 1 bit or bool flag to mark clients with that pattern can exclude the two `-`. There seems to be some structure in the values for those too which can additionally compress better (either via static lookup or dynamic runtime generated LUT), or some data structures (I forget the name, prefix trie?).

There's a Go implementation of zstd too, with a large enough sample set, you might be able to train the compressor on that and it may recognize the prefix part I just mentioned building a dict for you to compress with, but I think the remainder might be wasted on training (not sure, perhaps it'll recognize the limited charset and optimize for that?).

---

Just figured I'd chime in with that if it's helpful at all :sweat_smile:
