### ISSUE TITLE
Investigate 32-bit compatibility

### ISSUE THREAD

**Issue by pushrax** [chihaya/chihaya#56]
Currently it seems that there are some issues with running Chihaya compiled in 32-bit mode (e.g. #54). I don't see a good reason why we should drop support for 32-bit, so fixing these issues would be good.

**Comment by jzelinskie** [comment]
#54 seems to be resolved now, are we sure this issue needs to remain open? I asked the guys at Travis if they supported 32-bit so that we could add something to our CI, but they don't.

**Comment by jzelinskie** [comment]
@pushrax ping?

**Comment by jzelinskie** [comment]
I'll reopen this if we find any more evidence of these existing.
