### ISSUE TITLE
How to read metrics number?

### ISSUE THREAD

**Issue by encryptedxdata** [chihaya/chihaya#588]
Hi,
please what number is those?

Does it means for example 1.354391e+06 => 1.35 million?

Thx!
```
# HELP chihaya_storage_infohashes_count The number of Infohashes tracked
# TYPE chihaya_storage_infohashes_count gauge
chihaya_storage_infohashes_count 1.354391e+06
# HELP chihaya_storage_leechers_count The number of leechers tracked
# TYPE chihaya_storage_leechers_count gauge
chihaya_storage_leechers_count 1.846271e+06
```

**Comment by mrd0ll4r** [comment]
(replying via phone)I assume you're referring to the notation? That's scientific notation, i.e.,  something like 1.3 × 10^6, which is 1.3 million.Hope that helps. On Jul 20, 2022 16:33, encryptedxdata ***@***.***> wrote:
Hi,
please what number is those?
Thx!
# HELP chihaya_storage_infohashes_count The number of Infohashes tracked
# TYPE chihaya_storage_infohashes_count gauge
chihaya_storage_infohashes_count 1.354391e+06
# HELP chihaya_storage_leechers_count The number of leechers tracked
# TYPE chihaya_storage_leechers_count gauge
chihaya_storage_leechers_count 1.846271e+06

**Comment by encryptedxdata** [comment]
Thanks :)
