### ISSUE TITLE
Use cases for peer-to-peer cloud software deployments

### ISSUE THREAD

**Issue by josecelano** [chihaya/chihaya#611]
I'm looking for documentation, examples, etcetera, of using this software for peer-to-peer cloud software deployments.

**Comment by josecelano** [comment]
> * Chihaya

Hey, thank you @mrd0ll4r!

I was wondering if there are specific libraries for integration with other deployment tools.

For example, I guess one option could be to distribute your docker images with BitTorrent clients and use [docker save](https://docs.docker.com/engine/reference/commandline/save/) and [docker load](https://docs.docker.com/engine/reference/commandline/load/). You would need a thin BitTorrent client to "pull" the images. That way, you would not need to use a docker registry, and your servers would also act like a distributed docker registry.

But my question is more about already-built solutions than custom deployment processes. For example, maybe if you are using K8S you can setup a local docker registry and load images into the local registry with a "thin" BitTorrent client — just and idea.

Ideally, there should be an easy way to use the BitTorrent protocol in your standard deployment solution.

But I'm not a sysadmin, I'm just curious about use cases for BitTorrent. I'm also contributing to a [BitTorrent tracker](https://github.com/torrust/torrust-tracker), and I want to know more about real use cases.

By the way I found this client  https://github.com/mandreyel/cratetorrent that I suppose it could be use to write a service that you can run on your servers to download your artifacts.

I'm going to close the issue since this is more a discussion that an issue.

**Comment by mrd0ll4r** [comment]
Hmm, I'm not sure if there are ready-made solutions... I know twitter and facebook used to do some bittorrent stuff for their deployments, but not sure if that's still the case. I wonder if @jzelinskie knows more, since he's much close to what's actually happening in the industry :)
