### ISSUE TITLE
BadConnectionID errors are returned if the tracker is shutdown

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#72]
The tracker starts up and generates a random key to use for the generation of connection IDs for UDP packets, but if for some reason the tracker restarts or, if in the future, when clustering is available, traffic gets routed to another tracker, these keys will be different and clients will be served a "BadConnectionID" error.

This can be resolved by adding a key into the config and simply using that.

**Comment by pushrax** [comment]
I don't think this is a bug. The client should retry if its connection ID is reset. I also set it up to rotate all the IDs every hour, which is similar to what opentracker does.

**Comment by jzelinskie** [comment]
Maybe we should exclude this from the stats then? It seems pretty misleading.
