### ISSUE TITLE
Public tracker testing

### ISSUE THREAD

**Issue by rarbg** [chihaya/chihaya#78]
Just wanted to let you know that rarbg is now testing chihaya as a replacement for its current public tracker code running ~18mln peers.
I will post whatever we find as an issue here. If you find it useful - great , if you dont - great.
:)

**Comment by pushrax** [comment]
Awesome, great to hear. Definitely let us know if you run into any problems.

**Comment by rarbg** [comment]
Ok guys after running an unsuccessful short test here are my findings
1. Memory leak is deffinetly an issue. The tracker ate all available ram within 6 hours of operation. I can see the same ticket posted here https://github.com/chihaya/chihaya/issues/65
2. There is no blacklist/whitelist support , which is crucial to our operation
3. Persistent storage of hash info ( lets say how many times it was downloaded ) is not an option when you dont know go. I have no clue how to code the db layer from the noop driver :) I can only see Load* and RecordAnnounce , does that mean i have to put every announce in db and then process it via external scripts ? That will work on private sites but when you have 24000 announces/sec - it wont :P

**Comment by pushrax** [comment]
Great feedback, thanks.

Can you elaborate on what you mean by blacklist/whitelist? Do you mean by IP?

Storage drivers don't need to necessarily call out to a db, they could aggregate stats in memory and dump to disk periodically. Or it could use leveldb, boltdb etc. Open an issue describing the persistence you require and what performance characteristics are necessary and we can implement something that works.

**Comment by dtrackd** [comment]
@pushrax What @rarbg means is that they need the same sort of functionality as OpenTracker's `Closed Mode` (https://erdgeist.org/arts/software/opentracker/#closed-mode)

**Comment by rarbg** [comment]
By blacklist/whitelist i mean blacklist/whitelist hashes ( without restarting the tracker ofcourse )
When running in blacklist - dont allow announces/scrapes/anything for the blacklisted hashes
When running in whitelist - allow only those hashes to be announced

About the db :
A simple way to preserve counts in a db periodically ( counts of seeders , leechers , completed per hash ) 
A lot of scripts query that db instead of scraping the tracker.
Also on tracker "restart" in case of an issue or planned maintenance it will loose all completed count if there is no db attached to it

I didnt think you will respond so well on my "findings" so im also going to give you some more :)
We are not running opentracker or any other known public tracker code. Our code is our own coded in C ~50k sloc. Switching to chihaya will allow us not to maintain this heavy code anymore , even tho performance is better on ours.
What we are also missing as a feature is how PreferredSubnet works.
We not only have PreferredSubnet but also GEO + AS match.

Announce -> Try Subnet -> Try AS -> Try GEO -> Try random peers

**Comment by pushrax** [comment]
Opened https://github.com/chihaya/chihaya/issues/79 to track torrent whitelisting/blacklisting.

Matching ASN and geographical location is probably something we can include in core. @jzelinskie what do you think about that?

**Comment by rarbg** [comment]
Uh guys you dont need to fetch anything :)
http://godoc.org/github.com/abh/geoip

**Comment by pushrax** [comment]
@rarbg the way that works is by using the maxmind BGP dumps, which need to be kept fresh for accuracy.

**Comment by cooperlees** [comment]
I like this. I could then create my one daily 'maxmind bgp dumps' of my internal network to get better peers returned :)

Cooper

**Comment by rarbg** [comment]
@pushrax 
You will need maxmind for the GEO because allocation tables from RIRs dont guarantee a correct GEO :)

**Comment by pushrax** [comment]
@rarbg right – my earlier comment was about mapping ASNs.

**Comment by rarbg** [comment]
@pushrax 
:D and my comment was - why code 2 different things when you can use maxmind for both ?

**Comment by pushrax** [comment]
Good point. Do you know the format returned by `GetName` for an ASN?

**Comment by rarbg** [comment]
@pushrax 
It should return int or string with the net name depending on how it was implemented
I have no clue and to be honest i havent tested it because i cant code in go

**Comment by rarbg** [comment]
@pushrax 
I see there is no progress going... i guess you are very busy with other stuff
Can you just shoot the amount of $ needed in order for the features to be completed and the memory leak resolved ?

**Comment by jzelinskie** [comment]
@rarbg I can't speak for @pushrax, but I don't think money is an issue -- just time and a clear definition of the problems/features.

Can the sizes of your whitelist/blacklist fit into memory or is it something we should store in our primary storage (something likely backed with a db)?

**Comment by rarbg** [comment]
@jzelinskie 
Blacklists is the smallest of the issues , but yes they can fit in memory. But they also need to be stored in a permanent database as everything else should.... Memory is not really an issue (current memory pricing is cheap as f*ck) anyways as long as the memory leak ( https://github.com/chihaya/chihaya/issues/65 ) is solved.

**Comment by jzelinskie** [comment]
Closing this, as we determined there was no memory leak. The GC was simply not configured in a way @rarbg expected.
