### ISSUE TITLE
Blacklist Hashes for Public trackers

### ISSUE THREAD

**Issue by iBringit** [chihaya/chihaya#81]
Add option to blacklist hex or hashes that operators doesn't want to track.

Eg.. 
1. Someone sends a DMCA regarding a hash to be blocked.
2. Someone uploads a fake material and you want to block that hash.

This will be great to have as most trackers go down just because of a single or two or more hashes they are unable to block.

**Comment by dtrackd** [comment]
Dupe of issue #79
