### ISSUE TITLE
peermap is an abomination

### ISSUE THREAD

**Issue by jzelinskie** [chihaya/chihaya#88]
Way too much logic is in the `models.PeerMap` data structure and it is very coupled with the current memory storage implementation. If we want to use a persisted storage implementation, things would break because the peermaps are organized by the subnet config which could be changed between restarts.

I think we should push to simplify this stuff and get FB's subnet logic isolated into a specific driver implementation that they use.

**Comment by mrd0ll4r** [comment]
I agree with this. After reading the `tracker` package, especially `tracker/models/peermap.go`, it seems to me that the whole subnet logic is not a general tracker scenario/feature, so we should probably not include it in the core tracker package.

**Comment by jzelinskie** [comment]
Closing this as peermap won't be in 2.0.
