### ISSUE TITLE
`(*Announce)ClientID() string` is hard to understand

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#95]
This might just be a documentation issue, but: `(*Announce)ClientID() string` (in [tracker/models/models.go:170](https://github.com/chihaya/chihaya/blob/master/tracker/models/models.go#L178)) is very hard to understand without further explanation or examples.

I have later found the examples in the tests, that shed some light on the issue. However, after reading [this wiki article](https://wiki.theory.org/BitTorrentSpecification#peer_id) I'm not so sure anymore: The `peer_id` is client-chosen and there are no guidelines for generating it, it must only be 20 bytes long, right?  
If that's the case, the method documentation is wrong, or should at least elaborate further, for example that the string returned is not guaranteed to identify the client software or something like that...

**Comment by jzelinskie** [comment]
To my understanding ClientIDs, are essentially the wild wild west. @pushrax originally wrote that code for parsing it and has a lot of experience with seeing all of the popular client IDs in the wild. I'll await his response.

**Comment by pushrax** [comment]
There is no format, but in practise the first 6 (without any leading dash) bytes of the peer ID can determine the client.
