### ISSUE TITLE
(racy) double checking if a torrent has zero peers

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#97]
In [tracker/storage.go](https://github.com/chihaya/chihaya/blob/master/tracker/storage.go#L238-L244) and [tracker/announce.go](https://github.com/chihaya/chihaya/blob/master/tracker/announce.go#L66-L70) we check if a torrent has zero peers, then call `PurgeInactiveTorrent`, which also checks this.  
I'm not sure, but it might be that the access in `announce.go` is not synchronized, but it could also be that we work on a copy there.

I would remove the `== 0` check on both occasions and let `PurgeInactiveTorrent` do the check OR refactor the method into the calling methods (this is nice especially for `storage.go`, because `PurgeInactiveTorrent` repeats a lot of the steps already done there).

**Comment by jzelinskie** [comment]
>refactor the method into the calling methods

I'm not sure what you mean by this. Can you elaborate further?

**Comment by mrd0ll4r** [comment]
Sure, I thought about just pulling the two relevant lines

    atomic.AddInt32(&s.size, -1)
    delete(shard.torrents,infohash)

from `PurgeInactiveTorrent` into `PurgeInactivePeers`, and moving the check for `purgeEmptyTorrents && peers == 0` together with those two lines inside the synchronized... block(?).

This works in the case of `PurgeInactivePeers`, because we have all the synchronization and that, but will be difficult for `handleAnnounce`, because, as stated in the comment, "[r]ather than deleting the torrent explicitly, let the tracker driver ensure there are no race conditions" is a good idea...

But I'm generally really not sure about this approach. I mean, we have a method handling this, and should probably not start copying code where we don't have to...

**Comment by mrd0ll4r** [comment]
This does not apply to the new implementation anymore.
