### ISSUE TITLE
tracker/announce.go needs love?

### ISSUE THREAD

**Issue by mrd0ll4r** [chihaya/chihaya#99]
The whole flow of how an announce is handled is very spathetti-like, for example `handleAnnounce` is called with an announce, but that is filled and modified during that function, other functions in `announce.go` and even other functions somewhere in the models.

Additionally, the `Announce` type implies that this is the information sent to the tracker by the peer, but in reality it is much more like an internal data structure used to handle the announce on the tracker. Maybe we should introduce a type like `InternalAnnounce` and streamline the process of filling that out at the very beginning of `handleAnnounce` ?

**Comment by jzelinskie** [comment]
This code has been frozen and won't be in 2.0.
